### ISSUE TITLE
Deeper oceans

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1024]
Created a separate issue for this since #923 was going a bit off-topic

**Comment by jonqrandom** [comment]
i don't know if context for _why_ i would like this or how i plan on working around issues it may cause is helpful, so please ignore if you feel this is just blethering ;)

for starters, there's an obvious and massive inconsistency; RTG has wonderful, _soaring_ mountains and beautiful, massively elevated plateaus - by comparison, its "deep oceans" of 32 meters seem like paddling pools. i **would** just raise the sea level, but i've read (i think on mcf) that RTG is coded heavily around a Y63 sea level and doesn't really cope with anything much different. if i've taken that incorrectly, please do comment, because in that case i can always just biometweaker all the biome heights to fit something like a Y80-90 sea level.

still, understandably, a deep ocean that bottoms out around Y15-20 doesn't leave much room for an underground in regular minecraft, and with that little room left, there's no way to balance oregen against it without making deep ocean the "go-to" spot for easy, rich-pickings ore-mining. however, if both oceans and deep oceans can be deepened (and in fairness, the current Y-limit of 31 is plenty low enough for regular ocean), then as users we simply have the option to weight deep oceans lower so they don't eat into as much of the space available for oregen.

however, in my case (and quite possibly others'), i'll be using the "simple dimensions" and "world drop" mods along with custom presets or the underworld mod (or similar) to produce an entire caveworld underneath the overworld, thinning out the more valuable ores in the overworld, and adding a somewhat above-average generation as one progresses deeper in the caveworld, offset by an increase in dangerous mobs and environmental hazards. anyways, before i drift _too_ far off-topic, the point is that this setup also gets around the issues related to insufficient space for oregen underneath really deep oceans.

my apologies if none of this is any way useful or relevant.

**Comment by whichonespink44** [comment]
In theory, I'm all for making the oceans deeper, especially Deep Ocean. Back when RTG was in early beta, we had Deep Ocean going all the way down to bedrock in some areas. Obviously that created some issues with mod compatibility, but the main reason we don't go lower than Y=30 isn't because of mod compatibilities (those could  probably be worked around), it's because the lower the ocean, the more it drags down the neighbouring terrain, causing all sorts of headaches from what I understand. If we could find a way around that issue, then I'd be all for it, but if it's a case of choosing between deeper oceans or smooth, bug-free ocean biome transitions, gotta go with the latter.

**Comment by jonqrandom** [comment]
and since RTG doesn't touch biome layout, there's no way you can ensure deep ocean never touches a land biome, right? i understand that getting involved in biome layout is out of scope for RTG, so is there an easy way to only enable going under Y30 if the deep ocean in question is entirely surrounded by ocean/a certain distance from land?

by the way, was i correct about not being able to raise the sea-level without really ugly results? like i said, i'd be happy to adjust all my land biome heights upwards if that would work.

**Comment by whichonespink44** [comment]
As far as I know, adjusting the biome height with mods like BiomeTweaker has no effect on RTG's height map. The terrain noise for each biome is sort of 'hardcoded' even though all of the terrain is procedural, if that makes sense.

**Comment by jonqrandom** [comment]
yeah, i get what you mean, i could've sworn that is was, but then confirmation bias is a thing, so maybe that's all it was. i'll have to check when i can. 
come to think of it, when i tried setting ocean and deep ocean lower in BT, while deep ocean didn't change, regular ocean was often deeper and regularly hit Y30/31 - that's not supposed to happen usually is it?

**Comment by whichonespink44** [comment]
I think that might be confirmation bias as well.

Even though the minimum ocean floor is 30, Ocean has an average floor of [50](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/src/main/java/rtg/world/gen/terrain/vanilla/TerrainVanillaOcean.java#L16) and Deep Ocean, [40](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/src/main/java/rtg/world/gen/terrain/vanilla/TerrainVanillaDeepOcean.java#L16). I say 'average' because there's going to be some variance on both sides, which means it's possible for Ocean to get to 30 in the same way that it's possible for Deep Ocean to get to 50.

At least, that's my story, and I'm sticking to it! ;)

**Comment by jonqrandom** [comment]
yeah, like i said, i'll have to test it some more as soon as i can - would the best way just be to use the same seed and check ocean depths in the same places? or is changing terrain values likely to affect other stuff, therefore invalidating that method?

**Comment by whichonespink44** [comment]
Same seed, same place, new world... yep, that's the way to go... they should be exactly the same regardless of height settings.

**Comment by jonqrandom** [comment]
cool, i'll check that out once my new system is up and running, thank you :)

**Comment by srs-bsns** [comment]
There's no reason to keep this issue open as this would be a breaking change. It's already a part of the [1.11 TODO list](https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1116) and it will likely be backported to 1.10 if we decided to do anymore breaking changes there, but nothing like this will be backported to 1.7.10.
