### ISSUE TITLE
Volcano crash

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1025]
https://gist.github.com/MoeBoy76/13634c3a84d28a611b5e7f0b7fce8a7f

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/c32c606d4d12cb66c079ef9280a05e92309feeaa/src/main/java/rtg/config/rtg/ConfigRTG.java#L715-L718

This is probably a bad way to set the config defaults.

If BoP is loaded when rtg.cfg doesn't exist, the default will be set to a BoP block (ashBlock), and if BoP is then removed, the config setting will never reset, and will end in a NPE, since BoP won't exist. The same goes for UBC (which is usurped if BoP is also present and rtg.cfg doesn't exist).

However, the real issue (in **this** case) is two-fold.
1. There's no longer a mod with mod ID `BiomesOPlenty`, it's lowercase since 1.8.9 (biomesoplenty) :P
2. `ashStone` is a remnant from 1.7.10, this block was changed to `ash_block` (if that's actually the correct block, if not, then ash stone was removed).

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10%2B2-2.0.x/src/main/java/biomesoplenty/common/core/BOPBlocks.java#L120
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.8.9-3.0.x/src/main/java/biomesoplenty/common/init/ModBlocks.java#L79

**Comment by whichonespink44** [comment]
Fixed in cf7b626
