### ISSUE TITLE
[Feature Request] Make Sugar Cane Spawn More Frequently

### ISSUE THREAD

**Issue by chaNcharge** [Team-RTG/Realistic-Terrain-Generation#1059]
When I play a survival world with RTG, I'd expect to find sugar cane near lakes, rivers, and small ponds, but I cannot find a single sugar cane anywhere. In a normal minecraft world, it's somewhat easy to find, but I explore a world 500 blocks in each direction and have not found one sugar cane. There should be a config option on how frequently they spawn, or just simply make them more common. I am playing the 1.10.2 version of RTG with BiomeTweaker loaded using the BOP tweaks

**Comment by whichonespink44** [comment]
Added in 5f4ecd2

RTG now *attempts* to generate sugar cane as frequently as it attempts to do so in vanilla, with the exception of a handful of vanilla biomes where it generates slightly less.

The reason you're not seeing as much sugar cane is mainly because RTG generates fewer rivers and fewer lakes, meaning there are fewer valid spawn locations for sugar cane to generate.

For anyone reading this issue in the future... if you want more sugar cane, try increasing river and/or lake frequency in the configs to allow for more possible spawn locations.
