### ISSUE TITLE
CME when generating the world with a chunk generator mod

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1073]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

Chunkgen by Gecgooden (https://mods.curse.com/mc-mods/minecraft/235036-chunkgen)

- Forge version:

1614

- RTG version:

1.1.1.3

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Not easily replicable but try and generate a world using the chunkgen mod
2. ???
3. Possibly crash with this error: http://pastebin.com/fWEgy6gw

##### Extra Information:

http://pastebin.com/fWEgy6gw

**Comment by whichonespink44** [comment]
From what I understand, the ChunkGen mod is plagued with a few issues that make pre-genning painful. I'm not saying this is the reason for the crash, but we would recommend using AdminCommandsToolbox to pregen 1.7.10 worlds.

Since RTG doesn't support Thermos environments, I'm going to close this, but this line from the crash report might help in tracking down the problem:

```
Class transformer null safety: found misbehaving transformers: williewillus.BugfixMod.BugfixModClassTransformer(williewillus.BugfixMod.BugfixModClassTransformer@ddbab41) crashed with java.lang.NullPointerException(null)
```
