### ISSUE TITLE
NULL biome (52) found when growing an RTG sapling.

### ISSUE THREAD

**Issue by CrowAU** [Team-RTG/Realistic-Terrain-Generation#1080]
##### Affected Mod Versions: Biomes o Plenty, Twilight forest (Biome 52 is set to over grown mushroom biome from TF)

- Forge version: 10.13.4.1614
- RTG version: 1.7.10.1.1.1.3

##### Issue Description: 
Server crash on RTG sapling growth attempt

##### Steps to reproduce the issue:
1. Load server

##### Extra Information:
-http://pastebin.com/7BYty9T5  (crashlog)

**Comment by srs-bsns** [comment]
Twilight Forest biomes were not designed to be generated outside of the Twilight Forest dimension, therefore RTG does not support those biome in the Overworld. Generally, if you add an unsupported biome to Overworld generation, RTG will ignore it and generate vanilla plains, but it appears this has exposed a bug in the event for tree growth.

@CrowAU Actually, have you turned off the biome patcher by setting `I:"Patch Biome ID"` to `-1`?

**Comment by CrowAU** [comment]
So I've found out what caused the events leading to the crash. One of the members of my server was trying to do a rite of shifting seasons from witchery when a zombie showed up with a mushroom in hand, the zombie was killed the mushroom was dropped and transformed the area into deeps mushroom biome, Guessing a sapling then dropped and attempted to grow as one of those RTG trees causing the crash.

What a freak accident.

**Comment by whichonespink44** [comment]
@CrowAU It looks like you have [biome patching](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-master/etc/config/RTG/rtg.cfg#L32) disabled... as a quick fix you could enable that, and it should prevent that crash from happening again in the future.

As a more permanent fix, RTG should probably just throw a warning instead of crashing in situations where it's trying to grow an RTG tree in a null biome.
