### ISSUE TITLE
Villages placed on rivers

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Realistic-Terrain-Generation#1085]
##### Affected Mod Versions:
- Minecraft version: 1.10.2
- Forge version: 12.18.3.2185
- RTG version: 4.1.2.0
- GeographiCraft: 0.8.0
- Biomes O'Plenty version: 5.0.0.2109

##### Issue Description:
Villages are placed in river biomes on rivers while B:"Allow Villages" is set to false in river.cfg
I also noticed that there's no option for disabling villages in river biomes in geographicraft.cfg, and that leads me to the question: Does RTG override the geographicraft.cfg in terms of village placement generally / in the case of river biomes?

##### Steps to reproduce the issue:
1. Use GeographiCraft with config parameters given below
2. Generate a new world
2. Find a village in a river biome

##### Extra Information:
Seed: -83012481654173910 (village is a few steps to the east)

GeographiCraft config:
> B:NoBoPSubBiomes=false
> I:"Incidence of Continents,Large"=250
> I:"Incidence of Continents,Medium"=400
> I:"Incidence of Continents,Small"=200
> I:"Incidence of Islands,Large"=100
> I:"Incidence of Islands,Medium"=50
> I:"Land Expansion Rounds"=2
> B:SeparateLandmasses=true

![2016-12-14_14 04 58](https://cloud.githubusercontent.com/assets/22047030/21183455/4c5d8ab4-c208-11e6-8b1c-c9ccd3e5fda7.jpg)

**Comment by srs-bsns** [comment]
What village?

![2016-12-14_10 40 21](https://cloud.githubusercontent.com/assets/8453133/21188558/c94af256-c1e9-11e6-8da8-1d46518a2f2f.png)

This screenshot is from using only the mods you listed in this issue, but you are clearly using more than just those mods (I can see the TiCon slime island on your minimap). You are going to have to provide your latest log file as well, please.

Also, what is the location of the village well in respect to biome? When you stand on the well, what biome does it say you are in?

**Comment by whichonespink44** [comment]
I believe RTG overrides GC in terms of village gen.

Based on that first screenshot, it's possible that the village generation got triggered in a nearby Mesa biome (or Desert, if that's what the sandy areas are), and it just *looks* like it generated in the River. The biome of the well structure, as @srs-bsns mentioned, should reveal if that's the case.

**Comment by ghost** [comment]
Sorry, I forgot to mention I changed these options as well:
> I:"Maximum distance between villages"=40
> I:"Minimum distance between villages"=8

When I stand on the well, it says river, and I can confirm a village in the middle of a river in another world I tested yesterday.

It's reproducible without TC and the other mods.

**Comment by whichonespink44** [comment]
Since you said `"Allow Villages"=false` in [river.cfg](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/etc/config/RTG/biomes/vanilla/river.cfg#L131), we'll need to take a look at the 1.10.2 village gen code and see why this is happening.

My understanding from 1.7.10 is that a valid village-spawning biome can trigger a village up to 20 blocks away from the well, but this might've changed in 1.10.2.

**Comment by ghost** [comment]
Do you mean the well can be a few blocks outside of the valid biome? That would explain it, as there's always a little bit land near the village.

I think I will enable villages on rivers anyways and build valid foundations and bridges so it looks intentional.

**Comment by srs-bsns** [comment]
> Do you mean the well can be a few blocks outside of the valid biome? That would explain it, as there's always a little bit land near the village.

I'm pretty sure this is what happens with vanilla village placement. A biome check is made before the well is placed, though the well won't necessarily be at the exact location of the check. RTG's village generation is just a copy of vanilla Minecraft; The only modification we make is allowing a change to frequency and size.

In this case...
`[05:53:29] [Server thread/INFO] [FML]: [RTG-DEBUG] Potential village in Outback at 120 -344`
...the biome check is likely being made in an adjacent chunk to where the well is placed (in my screenshot, the 2 blobs of red sand (Outback) closest to the crosshairs are in adjacent chunks).

I'm not sure there's a good solution that doesn't require modifying the vanilla village gen code, which is kind of outside of the scope of RTG, and since the chances of this happening are rare(ish), the payoff isn't really worth the effort to remedy this.

---
> I think I will enable villages on rivers anyways and build valid foundations and bridges so it looks intentional.

I will advise against that, because RTG's river gen code creates lakes (sometimes large ones) that are all River biome (because there is no vanilla Lake biome.. gg Mojang), so enabling villages on rivers will just make it worse, because you will potentially get villages right in the middle of a lake.

**Comment by ghost** [comment]
> the payoff isn't really worth the effort to remedy this.

I agree. Thanks for your support and advice.

Please also have a look at the outback biome right north of that village. A river runs through it and it looks like the hills are placed somewhat on top of it. I know it's a BOP biome, but maybe you can do something about it, as it doesn't look realistic in that case - the river would erode the hills.

**Comment by whichonespink44** [comment]
No worries... we're currently re-working a few of the biomes for the next big update, so we'll take a look at the rivers as well while we're in there.
