### ISSUE TITLE
No Such Method Error Crash w/ Expedition Mod

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#1097]
##### Affected Mod Versions:

- Forge version: 2185
- RTG version: 4.1.2.1
- Expedition version: 1.3 Beta 8

##### Issue Description:

It crashes with the Expedition Mod mod on new world generation

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Launch the game
2. Start a new world

##### Extra Information:
- [Crash Log](http://pastebin.com/S0iU9y8S)

**Comment by srs-bsns** [comment]
From your crashlog: `UCHIJAA RTG{4.1.2.0} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.0.jar)`

You are actually using RTG 4.1.2.0. You need to update RTG to 4.1.2.1 as the newer versions of Expedition are updated to use the latest.

**Comment by srs-bsns** [comment]
CC: @WhiskyTangoFawks Since you are using reflection for your RTG compatibility, you should probably add some version range checking for RTG so people will get an error screen when they try to load a version of Expedition that isn't compatible with the version of RTG they are loading. A simple soft dependency check will suffice: `after:RTG@[4.1.2.1,)`, for example.

**Comment by WhiskyTangoFawks** [comment]
Good idea.   Done in my dev environment, will ship with the next release.

**Comment by whichonespink44** [comment]
@WhiskyTangoFawks I'll also try to make sure I give you a heads-up before we do a big update... ideally, RTG should be providing an API so you can do your thing, but that might end up taking a while. In the meantime, I'll just try to give some advanced warning before we update.

Speaking of which, we're planning to release a new version this weekend, but I don't think it's going to break anything this time as it's only minor tweaks and bug fixes at this stage. If anything changes we'll let you know.

**Comment by WhiskyTangoFawks** [comment]
The only thing I'm doing is getting out the tree array, and and calling individual trees to generate.  Now that I think about it would probably be simpler, and a lot less dependent on what you guys are doing to just put the tree generation cancelling I'm doing behind the simplex generation I'm already using, and just leave RTG to do it's thing instead of trying to interfere...

**Comment by WhiskyTangoFawks** [comment]
Alright, just FYI, as of 1.3.1 I've stripped out the RTG stuff from Expedition.  Instead of trying to meddle with getting and generating RTG's tree types, I've just cancelled the tree gen event based on a simplex generator to get a mix of RTG trees and mine.  Much simpler, and means I don't need to worry about compatibility issues with future updates.
