### ISSUE TITLE
Add support for vampireForest from Vampirism mod

### ISSUE THREAD

**Issue by maxanier** [Team-RTG/Realistic-Terrain-Generation#1165]
##### Affected Mod Versions:
- Minecraft 1.10
- Forge version: 12.18.3.2185
- RTG version: 4.1.2.4
- Vampirism version: 1.1.0-beta.2

##### Issue Description:

In my mod Vampirism I am using BiomeProvider#findBiomePosition to look for a custom/modded biome.
This works fine with the vanilla BiomeProvider, but when using RTG the provider returns a location at which there only is a different biome.
My code calling this function https://github.com/TeamLapen/Vampirism/blob/fe94d627dba4fd0f5f67073f03743f3610e335e9/src/lib/java/de/teamlapen/lib/lib/util/UtilLib.java#L395 (during [search](https://github.com/TeamLapen/Vampirism/blob/fe94d627dba4fd0f5f67073f03743f3610e335e9/src/lib/java/de/teamlapen/lib/lib/util/UtilLib.java#L412)).
I also was not able to find the biome without the command, but I did not have the motiviation to fly over the map for hours, so I just took a quick look.

Any ideas, what might be causing this? Is this related to the modded biome or is there a problem with your findBiomePosition implementation https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/965aa808cfa2bd84389beeb48131b027f3d40fe9/src/main/java/rtg/world/biome/BiomeProviderRTG.java#L281

I only tested this with 1.10, if you want I could try it with 1.11 as well if I find time.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Install any Vampirism version, e.g. the latest https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2410830/download
2. Create a RTG world in creative
3. Run /vampirism checkForVampireBiome

**Comment by srs-bsns** [comment]
In order for RTG to generate our custom terrain, we require custom biome classes that contain more data than the vanilla biome classes. Currently this requires that we manually add support for mods that add their own biomes to Overworld generation, and since we didn't know of your custom biome (and no one has suggested adding support for it yet) we don't currently support it.

 If you check your log file, you should see a line like this:
```
[11:08:53] [Client thread/WARN] [FML]: [RTG-WARN] WARNING! RTG could not find a realistic version of vampireForest (40) from de.teamlapen.vampirism.biome.BiomeGenVampireForest. (If vampireForest is a non-Overworld biome, then this is not an error.)
```
The biome layout will still contain your biome, but when it is encountered by RTG during chunk generation it will be automatically replaced with vanilla plains (default) if our biome patcher is enabled (default), otherwise the game would crash.

In the future we hope to add a feature that will provide a generic realistic biome class for biomes that aren't supported so that there will be basic support for any custom biomes automatically, but that feature will likely only be in versions for 1.11 and beyond. In the meantime, we could add support for your biome in 1.10.2, but it might be a while before we release a new version of RTG for 1.10.2 as our next planned release will be a major one with breaking changes, and that requires a lot of work and testing still. (@whichonespink44 may be amenable to putting out one more minor version before this though).

**Comment by maxanier** [comment]
Ok, thank you :)
Did not notice that

If you need any information to add this biome, feel free to ask.
RegistryName is "vampirism:vampireForest", Class is this https://github.com/TeamLapen/Vampirism/blob/374290008ec056775389443e1e69f5439b16939c/src/main/java/de/teamlapen/vampirism/biome/BiomeGenVampireForest.java.

**Comment by whichonespink44** [comment]
Added in 6c0dfc4
