### ISSUE TITLE
Chunk Unload and Reload loose living entities data/state

### ISSUE THREAD

**Issue by leagris** [Team-RTG/Realistic-Terrain-Generation#1168]
##### Affected Mod Versions:
- Forge version: either 13.20.0.2282 or 13.20.0.2296 can reproduce bug
- RTG version: 1.11.2-5.1.0.0-alpha 1 (_Alone, without any other mod_)

##### Issue Description:
Returning to already generated but later unloaded chunks; causes Living Entities to bug:
- Some entities (random) becomes immobile (no AI).
- Bugged entities can not be interacted with, (no push, no damage, no Villager deal on right-click).
Server log messages while this happens:
```
[Server thread/WARN]: Fetching addPacket for removed entity
```
As many times as you will find bugged entities.

##### Steps to reproduce the issue: (100% reproducible.)

1. Create an SMP Server with: either Minecraft Forge 13.20.0.2282 or 13.20.0.2296. and install RTG 1.11.2-5.1.0.0-alpha 1
2. Set [`server.properties`](https://gist.github.com/leagris/d5fab7f90d3ec91b9779694bbf876ad7) with:
```
level-type=RTG
level-seed=7007098431119981107
```
3. Start server and connect to world with client.
4. Reach near-by Village1 at `x=250, y=72, z=217`.
5. Visit distant Village2 at `x=2378, y=95, z=293` or go far enough so chunks containing Village1 gets unloaded by server.
6. Return to Village1 at `x=250, y=72, z=217`. See some villagers or other near-by animals bugged as described. See server console warning message about `Fetching addPacket for removed entity`.

##### Extra Information:

1. Bug only happens in SMP with `level-type=RTG`
2. Bugged entities are discarded on server restart.
3. Disconnecting/reconnecting client; retrieves same bugged entities unless server has been restarted. (see 2.).

**Comment by leagris** [comment]
In `config/forgeChunkLoading.cfg`
Setting `I:dormantChunkCacheSize=0` back to default; there is no more issue with entity bug on server.

**Comment by leagris** [comment]
Not invalid: Your mod can't cope properly with Forge dormantChunkCache. But other world generators do this properly. I had no issue with all other mods, but your's.
Neither User-Error
I spent the whole Sunday afternoon identifying your mod as the source of this mishandling.
The time I spent testing, reproducing, documenting this issue accurately sounds so worthless.
I am sick of those Jerks attitude.
Now you gave a good picture of your disregard for proper issue reports.
You told me you wanted to avoid RTG a bad reputation by not having that Alpha build into a mod-pack.
I think you just got it another bad reputation by tagging a real issue improperly.

**Comment by whichonespink44** [comment]
@leagris We appreciate the time you spent investigating the cause of this issue. It's clear that you were doing so in an effort to help make RTG better, and that kind of effort is very much appreciated, especially since we're a small team with limited availability, and we need all the help we can get these days. But please don't be offended by the way we've tagged this issue. It just helps us to add context to the issue without having to re-read the entire thread.

As for the issue itself... there's no denying that RTG seems to have a problem when `dormantChunkCache` is set to something other than 0, but it's such a narrow use case that it's not worth spending any more time trying figure out why.

If you Google 'dormantChunkCache', you'll see that RTG isn't the only mod to experience this odd behaviour when that setting is modified. [Issue #3325](https://github.com/MinecraftForge/MinecraftForge/issues/3325) on the Forge repo, for example, contains a mod list that doesn't include RTG, and they seem to be experiencing something very similar.

In any case, the time you've spent investigating hasn't gone to waste. Thanks to you, we're now aware of this particular issue, so if someone else experiences the same thing in the future, we can reference this issue and hopefully save them a lot of time.

**Comment by leagris** [comment]
It was just an ordinary bad day @whichonespink44 because the way it was closed and tagged improperly and the kind of phony discussion i had in Team-RTG Discord about this issue.

I can understand Forge's `dormantChunkCache` may be a borderline feature that's not well supported or that Team-RTG has not the time and resources to deal with it right now.

You mentioned similar Forge Upstream issue https://github.com/MinecraftForge/MinecraftForge/issues/3325 appropriately.

No: *It should not have been closed and tagged with such sub-class depreciating tags*.

This his how I expected Team-RTG to deal with it:

Keep issue open or on hold, add mentions and pointers to similar upstream bug reports; await more information upstream, either from Forge developers team itself or help from the Forge modders community.

Hopefully there are coding guidelines about supporting this `dormantChunkCache`;
- or there are more informed developers somewhere;
- or if the feature is incomplete/broken Forge side, it has to be documented!
- and the corresponding option into the config file, be tagged with an appropriate warning.

This is how it should work for any community opensource project like RTG.
Draw connexions with communities. Accept inbound feed-backs even if negative. Send feed-backs upstream as seems very appropriate here.

I am very sure Forge developers could appreciate such feed-back.
I am pretty sure other modders would be happy to enhance/fix their code to have better support for the feature.

**Comment by srs-bsns** [comment]
This issue was closed and tagged `invalid` because, as I, and others, have stated multiple times on Discord, that no RTG code is executed in any way during the chunk data saving and loading processes. It is irrelevant that it happens when RTG is loaded and doesn't when RTG is not loaded, and as has been stated, RTG is not the only mod that has had issue when setting `I:dormantChunkCacheSize` to a non-default value (non-0 value).

When you disclosed that you were using a non-default value for `I:dormantChunkCacheSize` and also that the issue you were observing was **not** occuring when `I:dormantChunkCacheSize` was set to `0`, your focus should have moved to Forge since this setting only affects how Forge works internally and has no effect on anything that RTG does. (Most people (including server operators) don't even touch Forge configuration because there isn't any reason to.)

This issue was tagged `user-error` to give it more context for searching through issues in the future. It might not convey the best context, but I wasn't going to add a new tag specific for this issue. It wasn't meant to be insulting or anything, just to convey that you were using a non-default configuration of Forge, and one that has a history of incompatibility with multiple mods.

For the above reasons, it serves no purpose, and would be a waste of our limited time, to explore this issue any further within the purview of RTG. All we can do is make note of it so that others can be aware to avoid non-default values for this Forge config setting.

I'm locking this issue because I don't want this issue to become a central point of debate. This can be discussed further on our Discord.

**Comment by whichonespink44** [comment]
mezz commented: https://github.com/MinecraftForge/MinecraftForge/issues/3897#issuecomment-301679236

> I was able to reproduce this with Forge alone, so it is a Forge bug.
