### ISSUE TITLE
Blend the transition from sand beach to stone/gravel beach so it isn't so abrupt

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1195]
Instead of this...

![2017-06-16_17 53 18](https://user-images.githubusercontent.com/10927161/27236582-6ac4358e-52bd-11e7-9640-daf7016be331.png)

It would be great if we could have something like this...

![2017-06-16_17 57 55](https://user-images.githubusercontent.com/10927161/27236605-7c2ad4c2-52bd-11e7-90f4-9cde2ce7e11e.png)

except much more natural looking, kinda like the surface bleeding that @topisani did for RTG2...

![](https://cdn.discordapp.com/attachments/168341623107878912/203662980355850240/2016-07-16_02.02.29.png)

**Comment by topisani** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/252337d7749cae4b607eb75cc097f69ae5934b25 There, thats RTG2 surface bleeding reimplemented, and only enabled on beaches.

There's a `TODO` in `provideChunk` because i don't know how to get the repaired biomes at that point. Without the repaired biomes, the surfacing is just broken with that commit

**Comment by whichonespink44** [comment]
Added in da399fa
