### ISSUE TITLE
WorldGen Crash

### ISSUE THREAD

**Issue by Yorkforce** [Team-RTG/Realistic-Terrain-Generation#1212]
##### Affected Mod Versions:
- Forge version: 2281
- RTG version: 4.2.0.0

##### Issue Description:
We encountered this crash report when generating new terrain, we had expanded our world border because the modpack we are using added ArsMagica2 to the pack and retrogen didn't appear to be working.
I'm not sure if this is a RTG issue, Sponge issue or one of the other mods, world gen seemed fine for everything else in previous versions of RTG and other mods however (excluding ArsMagic2)

##### Steps to reproduce the issue: (If it's easily reproducible.)
Generate new terrain

##### Extra Information:
Crash report:
https://pastebin.com/5xW3yizA

**Comment by whichonespink44** [comment]
@Yorkforce Thanks for reporting this. If possible, could you also provide your fml-server-latest.log file, and zip up your entire config folder and post that here as well?

**Comment by Yorkforce** [comment]
fml log might be a problem as the crash occurred 2 days ago and it doesn't backup the log file like it does latest.log, but when the server has no players on I'll try reproduce the crash and get you that log.

This is our config folder (were hosting the Mech and Magic modpack from ATLauncher btw)
https://www.mediafire.com/?1j1vv915ymkyrvd

**Comment by whichonespink44** [comment]
Thanks, we'll try reproducing this on our end. In the meantime, if you can't reproduce it yourself, feel free to send across whatever fml-server-latest.log file you have... just seeing what else is going on under the hood would be helpful.

**Comment by whichonespink44** [comment]
Ok, so I've been unable to reproduce this... and after looking at the stacktrace and giving this more thought, I'm confused as to what's going on here.

The reason I'm confused is mainly because of this line in the stacktrace:

```
at rtg.api.world.biome.OrganicBiomeGenerator.organicTerrain(OrganicBiomeGenerator.java:76)
```
The presence of this line suggests that RTG is trying to generate terrain for a biome for which it doesn't have inherent biome support. But since RTG has inherent biome support for Witchwood Forest from Ars Magica, I'm struggling to see why OrganicBiomeGenerator is getting involved.

Definitely need to see the fml-server-latest.log so we can rule out any unsupported biomes that might be getting added. If there aren't any unsupported biomes, then I suspect this may be a Sponge issue.

**Comment by whichonespink44** [comment]
@Yorkforce any chance you could post your fml-server-latest.log file when you get a sec? i'm still not able to reproduce this locally, so we're gonna need some deeper insight into what's going on behind the scenes if we're gonna be able to figure this one out.
