### ISSUE TITLE
RTG and magical forest conflict?

### ISSUE THREAD

**Issue by captcookie** [Team-RTG/Realistic-Terrain-Generation#1230]
1.10.2 Thaumcraft 6 beta
I used my nature compass and cannot find magical forest.

**Comment by srs-bsns** [comment]
RTG for 1.10 doesn't have support for Thaumcraft because Thaumcraft didn't even have a release for 1.10 until a few weeks ago.
There are no plans, currently, to put out another release of RTG for 1.10 that has Thaumcraft suuport as all focus is currently on porting RTG to 1.12.
Maybe after RTG has been ported to 1.12 this can be revisited.

**Comment by srs-bsns** [comment]
support added in https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/9acd884aba7910a9a35c9362694e4c0e375dc932
