### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by pap1723** [Team-RTG/Realistic-Terrain-Generation#1231]
##### Affected Mod Versions:
- Forge version: 1.10.2
- RTG version: 1.10.2 version

##### Issue Description:
I absolutely love the terrain that is generated by RTG, but I am running it with a decent sized modpack and I come across severe lag and performance issues when generating new chunks. I am wondering if there might be specific mods that cause this, or if it is expected behavior because of the nature of the terrain generation.

I would love to continue using RTG but cannot at the current level of performance I get. It is also possible I just don't have a beefy enough PC to handle it, but I don't think that is likely.

THANKS for any tips you can give!

**Comment by Robijnvogel** [comment]
You've only shared your Minecraft version.
Without knowing your **specific** RTG and Forge version, our hands are tied. 

Also, if you could share a complete list of your mods, preferably via pastebin or gist, that would be terrific. :D

**Comment by pap1723** [comment]
Thank you for your very quick response! Here you go!

https://gist.github.com/pap1723/ebe55faac5f24f68007017fb47e88ffd

**Comment by Robijnvogel** [comment]
Hmm, no snapshot, I see.
And do you not have these lag and performance issues when you aren't using RTG? 

And might I ask what your relevant hardware specs are? 
(allocated) RAM, CPU, GPU, Java version, 64 or 32 bit?

**Comment by pap1723** [comment]
What do you mean by snapshot?

I don't have perfect performance, but with RTG active, it is single digit FPS when I am traveling and chunks are loading.

RAM: 8,448 MB
CPU: i7-4790 @ 3.60 GHz
GPU: AMD Radeon R9 200 Series
Java: 8.0_161
64-bit

**Comment by srs-bsns** [comment]
This issue tracker is not for support requests, it is for bugs, which this is not.
For support like this, please join our [Discord server](https://discord.gg/anKT7YX), or ask in the [MCF thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes)

If what you are experiencing is only low FPS, then this issue is client-side, in which case it has nothing to do with RTG.

**Comment by StarSmasher44** [comment]
In all honesty, I can confirm FTB Infinity Evolved doing this with RTG enabled. The server effectively turned into a slideshow when chunks were being generated/loaded. I think it had something to do with trees loading/generating another chunk because they were too close to the edge, rinse and repeat you have a lot of new chunks being generated.

Ofc not sure if that is why it happens, I've read it somewhere.
