### ISSUE TITLE
Re-decoration Alps(BOP) for more epic and like VolcanicIsland(BOP)?

### ISSUE THREAD

**Issue by Marlect** [Team-RTG/Realistic-Terrain-Generation#1235]
I just thinks alps should be more epic than VolcanicIsland

VolcanicIsland in RTG: 
![2018-04-06_20 49 51](https://user-images.githubusercontent.com/33565913/38450966-b3f47014-3a59-11e8-88d0-2448cbd13987.png)

**Comment by srs-bsns** [comment]
This issue tracker is specifically for bug reports about RTG. For discussion about RTG you should go to our [MCF thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes) or join us on our [Discord server](https://discord.gg/anKT7YX)

---
When using BiomeTweaker with RTG, the Biomes O Plenty island biomes (which includes Volcanic Island) should not be added for generation as they will be improperly placed as inland biomes, instead of on islands where they are supposed to generate normally.

If you want these island biomes in your world, I suggest using GeographiCraft instead, as it has proper compatibility for them.

There will no longer be any changes for biomes in RTG for 1.10, and none of the terrains in their current state in the development branch are going to change for the upcoming release for 1.12.
