### ISSUE TITLE
Two code issues and a generation issue

### ISSUE THREAD

**Issue by brisingraerowing** [Team-RTG/Realistic-Terrain-Generation#1243]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 14.23.4.2705
- RTG version: 6.1.0.0-alpha.1

##### Issue Description:
Newer BoP versions (from 1.12.2-7.0.1.2361) have removed the polar chasm biome again, causing an error while building. [REDACTED]

I've also found Ocean Monuments generating under deserts (screenshot at bottom of post).

(I did a custom build to see what's what with the mod. I really like the generation.)
##### Steps to reproduce the issue: (If it's easily reproducible.)

1.
2.
3.

##### Extra Information:
![2018-06-15_01 52 12](https://user-images.githubusercontent.com/250409/41452314-571ea78a-703f-11e8-8d24-4cc8b8ea8660.png)

**Comment by srs-bsns** [comment]
I can understand people's impatience with wanting RTG for 1.12, and their enthusiasm for wanting to help, but srsly, please stop building RTG on your own.  It's not even near being ready for use, even for testing.
The `1.12-master` branch was only updated to be able to load in 1.12, but nothing in that branch has been updated.
The `1.12-update` branch, which is my working branch for updating, is a work in progress and won't even work.

I can guarantee that any bug or issue you could possibly find at the moment is already known and will be fixed before release.

The issue with BoP is already known and won't be fixed until a release is ready because I'm sick of having to update some code because Forstride wants to make some breaking change on a whim.
The monument generation issue is already known: #913

**Comment by brisingraerowing** [comment]
Thanks. I'm probably going to remove it, I just wanted to see what was up.
