### ISSUE TITLE
[Request] Configurable height limit

### ISSUE THREAD

**Issue by tridaak** [Team-RTG/Realistic-Terrain-Generation#1246]
##### Affected Mod Versions:
- RTG version: 4.1.3

##### Issue Description:
Not an issue rather a request, RTG creates massive mountains which often times look great, however often times you'll have a desert or a jungle with a small hills area which leads to a giant mountain in the middle of nowhere. Was wondering if there could be a setting to scale the height of the terrain, so people could make flatter worlds if they need to, or if they want it to be extreme, they set the scale really high.

Another option to this that I was thinking, that could possibly be better and easier for server owners to understand and apply would be terrain height limit per biome. If someone wants tall extreme hills like usual, but wants relatively small hills in desert and jungle areas this could do that.

**Comment by whichonespink44** [comment]
Not sure if this is possible since the terrain algorithms don't really have a single variable for height. The one exception to this is the 'Dune Height' config option, which modifies the height of the dunes in vanilla Desert, but the other terrains are more complicated and don't really lend themselves well to customizable heights.

**Comment by srs-bsns** [comment]
All of the terrain routines that create mountains, etc, used hardcoded values, and it would be more work than it is worth to change this.
Also, this would be a breaking change so it would not happen in 1.10 anyways.
