### ISSUE TITLE
RTG is not working with CC

### ISSUE THREAD

**Issue by Endriex** [Team-RTG/Realistic-Terrain-Generation#1258]
I have installed Realistic Terrain Generation, Biomes O'Plenty and Climate Control. 
The CC with default world type is working correctly (I tried to turn off vanilla biomes and turn on BoP biomes in CC config file) but with realistic world type is not working. It only spawns vanilla biomes used only from RTG. I tried to remove certain biome from vanilla biomes in CC... Still nothing.

Listed Mods:
BiomesOPlenty-1.7.10-2.1.0.1826-universal
climatecontrol-04beta98142329
CodeChickenCore-1.7.10-Latest
Flans Mod-1.7.10-4.10.0
JourneyMap-Mod-1.7.10-FairPlay
NotEnoughIDs-1.7.10
Not-Enough-Items-1.7.10-Latest
Not-Enough-Keys-Mod-1.7.10
OptiFine_1.7.10_HD_U_D8
Realistic-Terrain-Generation-Mod-1.7.10
Waila-Mod-1.7.10
WorldEdit-1.7.10

Any ideas?

**Comment by whichonespink44** [comment]
Can you Pastebin your Climate Control config files?

**Comment by Endriex** [comment]
Yup.

https://pastebin.com/raw/b0SKwJR4

**Comment by Endriex** [comment]
Someone has a solution? Maybe RTG needs special code to run CC

**Comment by srs-bsns** [comment]
Judging by the look of the mod list you provided, (if those are the filenames of the .jars,) you have been downloading mods from nefarious sources, such as 9minecraft.com.
Unless a mod has it's own website, you should only download mods from a reputable source, such as Curse/CurseForge.

Regardless, I can tell you that the version of ClimateControl you are using is **extremely** old, even with respect to 1.7.10, and it is an early beta version. You should be using the latest versions of all mods.

[RTG-1.7.10-1.1.1.7 on CurseForge](https://minecraft.curseforge.com/projects/realistic-terrain-generation/files/2521557)
[ClimateControl 0.8.2 on CurseForge](https://minecraft.curseforge.com/projects/climate-control-geographicraft/files/2359685)
[BiomesOPlenty-1.7.10-2.1.0.2308 from their Maven repo](http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/1.7.10-2.1.0.2308/BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar)

Those versions should work fine together.

I'm closing this because if there were any serious issues between RTG and CC and BoP, they would have been fixed long ago. Any other issue will not be fixed as RTG-1.7.10 has been out of development for quite some time. Any issue with CC will likely not be fixed as the author is no longer active anymore and his code repository for CC has not been update for a very long time.

**Comment by Robijnvogel** [comment]
Excuse me @Endriex but where did you download these mod files?
It seems like the mod versions that you listed came from the mods' file names.

And it seems like there is no official release file name that matches, for instance, the name of the Waila or Climate Control version that you listed.

**Comment by Robijnvogel** [comment]
Darn you, mister Business...
You sniped me.
