### ISSUE TITLE
A grab bag of various mods to support

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1283]
1. Thaumcraft
2. Dynamic Trees
3. Traverse
4. Novam Terram
5. Terra
6. Vampirism

There are probably more biome-adding mods I can think of, and I'll add them here as I find them.

**Comment by srs-bsns** [comment]
Thaumcraft support is already added in dev
Traverse support is planned and will be added eventually.
Any other mod support that was in 1.10 will be readded if there are 1.12 versions of the mods.
Dynamic Trees - This can't happen in RTG, because it requires a client-side component.
Terra is discontinued and was replaced by Novam Terram, so Terra support isn't going to happen.

**Comment by Sunconure11** [comment]
Hm, what about Ice and Fire? It has one biome, a glacier biome.

**Comment by whichonespink44** [comment]
Yep, we had support for that in 1.10.2, so that will be migrated across as well.
