### ISSUE TITLE
Water/Lava Spout config doesn't work, possibly others

### ISSUE THREAD

**Issue by Circine** [Team-RTG/Realistic-Terrain-Generation#1345]
##### Affected Mod Versions:
- Forge version: 14.23.5.2847
- RTG version: RTG-1.12.2-6.1.0.0-snapshot.1

##### Issue Description:
Water and Lava Spout config settings are ignored. They continue to spawn underground in large numbers even when disabled in the world customization menu. Can't even get rid of them with BiomeTweaker in an RTG world.

Not as important to me but the per-biome surface block replacement configs don't seem to work either. I thought I'd be able to remove things like the cobblestone from Extreme Hills but even changing all of them to a single block like clay shows no differences. Disabling RTG surfaces causes everything to be solid stone rather than using vanilla blocks.

**Comment by srs-bsns** [comment]
The generator and config options were not updated to reflect certain changes that were made in RTG for 1.12, so there are some options that no longer do anything.

The generator option to disable spouts was disabled because it is something that is handled during biome decoration and so didn't really belong where it was. This is also something that is not configurable in vanilla and was only added to RTG to prevent the spouts that generate on the side of hills/mountains and create 'skirts' of water/lava down the side which look horrible.

With the new generation spouts will mostly only generate below ground and the ones that generate above ground are quite limited and can only generate at low elevation. (Water spouts only generate between y:8-72, Lava between y:8-80, but lava spouts use a recursive RNG so they will generate more abundantly at lower y levels.) Also, the generation attempts per chunk have been lowered to 20 (water) and 5 (lava) from vanillas 50 and 20.

There are no plans at this time to make it configurable again.

You should still be able to get rid of them with BiomeTweaker by using block replacement set to happen after biome decoration, however this will also replace underground lava lakes, which may be undesirable. The block replacement should be limited to a y-level above 11 so that it won't interfere with the normal lava that generates near the bottom of the world, otherwise the world wouldn't have any lava at all.
