### ISSUE TITLE
Is this mod working with otg ? 

### ISSUE THREAD

**Issue by DamienBrittan** [Team-RTG/Realistic-Terrain-Generation#1354]
Is this mod working with otg ? (sorry for posting here , but there's no comment section at curseforge)

**Comment by srs-bsns** [comment]
Comments are disabled on Curse because we prefer to use Discord as our single point of support.

RTG will not work with OTG because both mods require the use of a custom chunk generator, and only one can be in use at a time for a world.

For further questions, please ask on Discord: https://discord.gg/anKT7YX
