### ISSUE TITLE
Compatability With Beyond the Veil

### ISSUE THREAD

**Issue by Darkfiend009** [Team-RTG/Realistic-Terrain-Generation#1356]
Beyond the Veil - https://www.curseforge.com/minecraft/mc-mods/beyond-the-veil - is a new magic mod that adds a biome and it's own version of a village. I don't believe that it is actually registered as a village as it's customized NPCs that the dev has in there. It's a story based mod and one of the NPCs helps progress the mod from that biome.

We've been unable to locate the biome in our recent modpack Emergence which features RTG (which we love, btw). I checked the config folder for RTG and noticed that there was no registered config file for the biome in Beyond the Veil, so i am assuming that's why we can't find one.

Is it possible to add support for Beyond the Veil?

**Comment by Dthen** [comment]
I have been using RTG and Beyond the Veil and have ran into the Voided biomed several times.

**Comment by SPYROHAWK** [comment]
I know it's been a few months but I'm having the same issue. I talked to the creator of that mod on reddit and the full issue report can be found here: https://www.reddit.com/r/BeyondTheVeilMod/comments/j9l0iq/question_for_recommended_fix_1122/

The issue seems to be nature's compass, as well as BTV's own biome location ritual, is giving coordinates that lead to, well, not the voided biome (for me it's always plains). Since the above poster said it they ran into the Voided biome, we think it might be an issue with RTG messing with the biome location techniques, but pushing the biome spawn rate all the way up still yields nothing.

**Comment by Dthen** [comment]
Odd. I don't think I had Nature's Compass installed at any point.

**Comment by srs-bsns** [comment]
When RTG encounters a biome that it does not recognize (for which compatibility has not been added) then it will generate that biome as `minecraft:plains`.
Also: https://github.com/Team-RTG/Realistic-Terrain-Generation/pull/1370#issuecomment-1119683669
