### ISSUE TITLE
Unfinished meteors and possible more

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#156]
I THINK i found the bad guy causing this issue.
As far as i know this only happens to the RWG biomes and i think the bad guy is:
 
  @Override
    public void rReplace(Block[] blocks, byte[] metadata, int i, int j, int x, int y, int depth, World world, Random rand, PerlinNoise perlin, CellNoise cell, float[] noise, float river, BiomeGenBase[] base)
    {
    	surface.paintTerrain(blocks, metadata, i, j, x, y, depth, world, rand, perlin, cell, noise, river, base);
    }

This line is at the end of all those realistic biome files.
I gonna test some things out to be sure.

**Comment by whichonespink44** [comment]
Cool, let me know how it goes!

**Comment by Ezoteric** [comment]
Didnt work out, still created volcano at the biome it lays next to, also incomplete on a BOP biome.

So still dont know whats the problem :P

**Comment by whichonespink44** [comment]
I've just been testing this with the latest version of RTG (0.0.13), and whilst there are still some meteorites that are smaller than normal, I've found plenty that were full size. And even in the smaller, unfinished ones, the sky stone chest was always intact so I don't think this is an issue anymore. In fact, I think it's kind of 'realistic' that the meteorites aren't always the same shape and size. :)

**Comment by Ezoteric** [comment]
It's not realistic when it's cut off in a 90° angle unless prehistoric ppl cut it that way like the Egyptians did in our world :p  hahah

**Comment by whichonespink44** [comment]
Are meteorites still getting cut off like that in the latest version? I found 12 meteorites yesterday and about half were full size, and the other half we just smaller than normal, with no weird stuff going on.

**Comment by Ezoteric** [comment]
Oow I dunno haven't checked the latest version yet. But the sizes always where random.
So what your saying is you fixed meteor generation? :o

**Comment by whichonespink44** [comment]
It would appear that way, though I didn't do it intentionally :smile:  I only tested it with RTG 0.0.13 and AE2 installed (no other mods), so it's possible that another mod's biomes might still have the issue, but I can always re-open this issue if that's the case.

**Comment by Ezoteric** [comment]
Besides ae2 I also have witchery on and chisel in my test mc.

Btw something else. Is it possible to approach decoration for vanilla biomes like we do with support like bop and stuff? Cause if so that might be a fix we can use. That way we can just usenough genlayer and everything works like a charm ? :p

**Comment by whichonespink44** [comment]
Not sure what you mean... approaching vanilla decoration like I do with BOP, that's the exact opposite of what I've been doing for the last couple of weeks. :P  In order to prevent crashes, and in order to achieve the RWG look, I need to manually decorate ALL biomes (vanilla & modded), so the 'support' approach will be getting phased out over the next few releases. Unless you meant something else?

As for GenLayers, I've given up on them for now, possibly forever. They're just too complicated for what I'd be using them for (islands/beaches), and I'm pretty sure I can do both of those without GenLayers. Just haven't figured out how to do it yet. But I'm still learning more & more each day, and I finally feel confident enough to ask for help on the Forge forums, so it won't be too long before I figure it out.

As for hot-to-cold trsnsitions, I've made some progress in that area... just want to resolve all these crashes that RTG's been getting lately. Need to make sure the foundation is stable before changing it up again.
