### ISSUE TITLE
BiomeBase.java

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#182]
hey i am seeing biome climate and categories but aint we need to use just 1 of the 2 ? :P

PS why cant i label anymore :P

**Comment by whichonespink44** [comment]
Eventually we'll probably just use one of the two, but they're each doing slightly different things at the moment. Still not sure what the best approach is here (mainly because I'm still trying to work out what's going on in the ChunkManager file. That's the part of the rewrite I'm looking into now. I need to understand better what's going in the ChunkManager and ChunkGenerator files before I can carry on with the rewrite.

As for labels... can you not assign labels anymore?

**Comment by Ezoteric** [comment]
Yeah and than there is gen layer also what I think does almost the same thing haha.

I'll try and test some Shit tomorrow and see if I can understand some parts haha


And weirdly since you made team u can't :(
