### ISSUE TITLE
this might be sad...

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#206]
I have no idea anymore but it doesnt look good with using surface in the biome file it self.

I know the chunk provider does almost all the work but when you dig deeper into layers and how shit really works it gets confusing as things dont add up anymore.
some mc biome files have decoration in there some dont, you have a biomedecorater file that prolly does something, and the more you diggin the more weirder it gets.

I really hope this is gonna work but so far im getting hopeless :(

**Comment by whichonespink44** [comment]
I've booked most of the day off, so I'll be working on this today. I spent about 30 minutes after our IRC session last night, and I think I understand what needs to happen a lot more now. I'll keep you posted.

Don't give up hope!! :seedling:

**Comment by Ezoteric** [comment]
It's not that I'm giving up its more that the only thing I ever did was trying to understand what does what and look at other mods to compare.  And I think I hit a roadblock cause the lack ofor real.knowledge about this code haha btw when your home maybe it's a good idea to talk on the mic for a  few minutes so I can tell you what I found out and what you found out and hope that will sync

**Comment by Ezoteric** [comment]
Btw something else what's weird is:
I generated a default map as in generator setting on default with RTG still in my mod folder. The map I generated had mushroom shore in the middle on normal biomes. So I took RTG out of my mod folder and re-created the map and it was totally different. So my question is, if we don't use the world type of RTG it shouldn't be doing things in our world right? But it does....

**Comment by whichonespink44** [comment]
you mean it generates realistic terrain in the default world type? :O

**Comment by Ezoteric** [comment]
I don't know cause we don't have that stuff with gelayers but it does make the world weird and definitely not default

**Comment by Ezoteric** [comment]
well trying to do it with the rwg manager and provider with genlayer enabled in the manager files and generating a map now, but i allready saw some weird shit happening :(

**Comment by whichonespink44** [comment]
_"well trying to do it with the rwg manager and provider with genlayer enabled in the manager files and generating a map now, but i allready saw some weird shit happening"_

Any luck?

I have to say... I've been spending a lot of time on this today, without any luck whatsoever.... so... what would you say if I told you I was thinking about ditching the genlayer approach?

Cuz here's what I'm thinking...

RTG only has 2 major issues at the moment, right?

1. Mushroom Islands not generating in the ocean
2. Preventing hot-to-cold biome transitions

I mean, if we can solve those 2 issues, then RTG is pretty much ready for Beta, right? (I know we want RTG to do more, but I'm just talking about Beta here)

So here's why I think we should ditch genlayers:

* Genlayers are hard!!! :stuck_out_tongue_winking_eye: 

* Surely we'd have better luck keeping the RWG foundation (which is already working pretty well) and trying to solve those 2 problems, rather than trying to rewrite the entire foundation (using an advanced system that neither of us really understands), only to then have to import the RWG foundation back into it anyway.

* Those 2 problems listed above are actually just one problem.... if we could come up with a system whereby we can whitelist/blacklist biomes for transition, then we solve the hot/cold issue... and we also solve the Mushroom Island issue because we can just say that Mushroom Islands can only transition into Mushroom Island Shore.... and Mushroom Island Shores can only transition into Ocean, Deep Ocean, and Mushroom Islands.

Don't get me wrong, if someone came along and said, "Oh, gen layers? Yeah, they're easy - here's a pull request with everything working." then I'd be like, "SWEEET!!", but.... that isn't likely to happen because they're complex, and might not even compatible with everything else we want to do in the future.

What do you think?

**Comment by Ezoteric** [comment]
Well, i have no idea if it will be that easy to fix with the island. 

either way, i dont mind if we use gen layers or not as long as everything can work out.
Im also affraid that some mods might not be compatible cause we dont use a lot of MC.

And yes we deff need some smart java ppl up in this group :P

**Comment by whichonespink44** [comment]
_"PS: irc is on :P"_

You sure? It's just me in there at the moment: http://webchat.freenode.net/?channels=#RTG
