### ISSUE TITLE
Configurable hardcoded blocks for surface decorations

### ISSUE THREAD

**Issue by Muramasa-** [Team-RTG/Realistic-Terrain-Generation#235]
![image](https://cloud.githubusercontent.com/assets/7321570/10649510/752caf40-783c-11e5-824a-60a7f1182e6f.png)

It would be really awesome if UBC was installed RTG would use the cobble variant of the UBC stone where it generates vanilla cobble.

Extra Feature: If spawning UBC cobble where vanilla cobble is spawned is possible, then could a mix of vanilla and UBC cobble be an option? The reason for this is because on some stone types, vanilla cobble does actually look nice against UBC stone.

I am really not sure how possible this is but I thought I'd see what you thought.

Thanks.

**Comment by whichonespink44** [comment]
Hmmm.... at the moment RTG hardcodes a few blocks when it's decorating some of the biomes (cobblestone being one of them), but I'd like to eventually get rid of all of those hardcoded blocks at some point. Unfortunately, until the API is finished, that won't be possible.

In the meantime, I could possibly add a config option that allows you to choose which block gets used in those hardcoded situations. For example, I'm not sure what biome that screenshot was taken in, but let's just say it's Savanna Plateau, which hardcodes cobblestone to be used as one of the cliff blocks. In the config files, I could put an option called `"Block to be used on rock cliffs instead of Cobblestone"` and then you could enter the ID of the block you want to use... so in this case you might put `"ubc:igneousCobblestone"` (or whatever the ID would be). That would then replace all hardcoded instances of cobblestone with that UBC block.

Ideally, this would want to be configurable on a per-biome basis, but I could probably add it on a global basis to start off with, if that's something you'd be interested in?

To do anything more dynamic, like using a mixture of vanilla and modded blocks would require the API to be finished.

Sorry @Muramasa- I know that's a lot of rambling on my part, but let me know what you think of the 'global basis' option above and I'll see what I can do.

**Comment by Muramasa-** [comment]
To be honest, for this specific feature doing it via a config might even be a better option... I didn't think of that.

So having a per-biome config option sounds amazing when you can find time to get around to it and that would even add another layer of customizability if that worked on all of the biomes that RTG supported :D

Again, thanks for all the detailed replies you give! (my username on the mc forum is Tak)

**Comment by whichonespink44** [comment]
No worries - I doubt I'll get it in the 0.0.13 release, but it's something I've wanted to do for a while, so I'll definitely try to get in for 0.0.14.

**Comment by whichonespink44** [comment]
I've setup the foundation for this in the latest branch that I've been working on. At the moment, there's just one config option to allow you to change the 'shadow' block that's used on mountains (in the latest release, it's hardcoded to cyan stained clay), so if it goes well in the next release (i.e. doesn't cause any crashes), then I'll use the same system for the other hardcoded blocks as well.

**Comment by WelcomeToJamBox** [comment]
Adding an option to use UBC's stone biome would be pretty easy, if the cobble is added at chunk population (don't know if it is). I personally wouldn't use it I like the contrast of vanilla cobble.
But, I reckon it would be nice for some people. Just, need UBC API column provider get the stone cobble version.

**Comment by whichonespink44** [comment]
Full support for UBC has been requested and accepted in #321.
