### ISSUE TITLE
Emeralds generated in the world

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#254]
I found a generation of emeralds.
However, in the configuration, this function is disabled.

    #  [default: true]
    B:"Generate Emeralds"=false

Worth CofH. But there is no generation of emeralds.  RTG-1.7.10-0.0.13
![2015-10-31_13 04 07](https://cloud.githubusercontent.com/assets/6783568/10863267/2ca70c84-7fd0-11e5-9282-58b18e1ffc5b.png)

**Comment by whichonespink44** [comment]
Can you provide a list of mods, and the `fml-client-latest.log` please?

**Comment by Tsyklop** [comment]
@whichonespink44 

Mod-List: http://pastebin.com/3sK47Zpj

Log: https://gist.githubusercontent.com/Tsyklop/f3544b390df96e5a9d0f/raw/34abd7d98d2df0a96860f75689d3ef01fe1dd117/gistfile1.txt

**Comment by whichonespink44** [comment]
Thanks for the details.

How did you get so many emeralds to generate? I'm pretty sure it's another mod causing them to spawn, but you've got way too many mods for me to work through.

The good news is that I've made quite a lot of improvements to the way chunks are generated, including how ores are generated, so there's a good chance this will be fixed in 0.0.14, due to be released tomorrow.

**Comment by Tsyklop** [comment]
@whichonespink44 This is CofH generation. I made it.

**Comment by whichonespink44** [comment]
Fixed in a5a48df

**Comment by Tsyklop** [comment]
Thx!

**Comment by Tsyklop** [comment]
Not be fixed(

RTG 0.15 - emerald generate
