### ISSUE TITLE
[Suggestion] Add support AE2 metiorite

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#264]
Please. Add support for Metiorite spawning from AE2

**Comment by Ezoteric** [comment]
This already works....  I have ae2 in my test environment and it does spawn

**Comment by whichonespink44** [comment]
Yep, they've been generating since version 0.0.1

@Tsyklop - have you tried grabbing a meteorite compass from the creative inventory? That's how I usually do my AE2 testing, though sometimes they can spawn underground, which isn't a bug with RTG - just the way AE2 spawns them sometimes.

Let me know how you get on.

**Comment by Ezoteric** [comment]
Is that a bug ? I find it pretty realistic as it could be there for centuries while others are newer right :)

Also I think I posted some pics in the RTG forumpage and you will see meteorites ;)
