### ISSUE TITLE
Strange generation bug

### ISSUE THREAD

**Issue by Sirse** [Team-RTG/Realistic-Terrain-Generation#270]
Hi! Sorry me for my bad english.
I see strange terrain generation bugs: 
![2015-11-10_12 56 57](https://cloud.githubusercontent.com/assets/3335371/11116633/1919ab30-895e-11e5-8280-b360e599cebb.png)
![2015-11-10_12 57 46](https://cloud.githubusercontent.com/assets/3335371/11116635/191e4b36-895e-11e5-8e74-f40a7497e4bb.png)
![2015-11-10_12 58 57](https://cloud.githubusercontent.com/assets/3335371/11116634/191d32fa-895e-11e5-8f01-5355d7435345.png)
Bug don't affect to all my world, only in some places.

Also, you can get information about my modlist/configs/server here - https://drive.google.com/open?id=0BzR1i4u-G1JsU2NzclJZT21Lbzg

**Comment by whichonespink44** [comment]
Thanks for reporting this.

I tried to download the modlist/configs/server but I didn't have permission, so I've requested access via Google Drive.

**Comment by Sirse** [comment]
Sorry, my fault, try this link - https://drive.google.com/file/d/0BzR1i4u-G1JsU2NzclJZT21Lbzg/view?usp=sharing

**Comment by whichonespink44** [comment]
Awesome, thanks. I'll look into it and let you know if I find anything.

**Comment by Sirse** [comment]
Any news about that problem?

**Comment by whichonespink44** [comment]
Just been looking into it now... it looks like RTG's biome selection is 'falling apart' because it doesn't have enough biomes from each 'category' to choose from. In your case, you've disabled all vanilla biomes, and the only BOP biomes that you've left enabled are from the 'WET' category (biomes with temperatures greater than 0.3 and less than or equal to 1.0).

The way biome selection works in RTG, it basically needs at least one biome from each category enabled. It's not ideal by any means, but that's where it's at currently, unfortunately.

So... the only fix I can offer you at the moment is to enable at least one biome from the other three categories (SNOW, COLD, HOT).

Here's some debug output that has all the biomes as they're being added to the biome pool: https://gist.github.com/whichonespink44/c779cc7cd390368036de

Hopefully I'll be able to improve the biome selection process in future releases, but in the meantime hopefully this will work for you.
