### ISSUE TITLE
Snowy Coniferous Forest has too many huge mountains.

### ISSUE THREAD

**Issue by Claycorp** [Team-RTG/Realistic-Terrain-Generation#309]
There really isn't any trees at all in the biome (except a few in the valleys between mountains) as it mainly consists of huge mountains up to Y200-250

It looks cool as heck but seems wrong for a forest. 
Example: http://i.imgur.com/d6szPxA.jpg everything there is the same biome.

**Comment by Ezoteric** [comment]
Ikr haha also some mountains should be less steep ;)

**Comment by whichonespink44** [comment]
I'm currently re-decorating the EB biomes so that I can hopefully have them all using EB's stone/grass/dirt in time for the next release.

After EB's biomes have been re-decorated, I'll go on a BOP blitz and try to get all of those re-decorated as well. (And yes, I agree, there are way too many huge mountains in BOP biomes.)

**Comment by Claycorp** [comment]
WOOO! Keep up the good work! Less mountains will make all CPU's much happier :P

**Comment by whichonespink44** [comment]
Fixed in ed4c061
