### ISSUE TITLE
Edge biomes don't generate along the edges of their related biomes

### ISSUE THREAD

**Issue by frederick-the-nameless** [Team-RTG/Realistic-Terrain-Generation#327]
For some reason certain edge biomes seem to generate like normal biomes instead of edges. I've noticed this with stone beaches and jungle edges so far.

**Comment by whichonespink44** [comment]
Yeah, this is a known issue but I forgot to add it to the issue tracker.

Currently, RTG treats edge biomes just as it does any other biome, but ideally this is something that I'd like to resolve.

**Comment by Ezoteric** [comment]
Yes we know cause that way we can do a lot more with main biomes like savanna valley 😉

**Comment by Kehaan** [comment]
Have sent you whichonespink a message on the minecraftforum, but i just say this in the issue tracker. Is this the same issue i am having? Using 0.1.0 i get https://gyazo.com/ebd3bf2750aff415cd7e9b56ce5a7886
Using 0.2.0 i get https://gyazo.com/520bb33da47156b1d0d636aa200d3dad instead :P

**Comment by whichonespink44** [comment]
@Kehaan That's a slightly different issue... this issue is related to Jungle Edge biome, for example, not always generating next to a Jungle biome.

I had hoped the issue in your screenshots was resolved in 0.2.0 with the memory-handling improvements, but it looks like it's still an issue.

Can you create a new issue for this please?

**Comment by Kehaan** [comment]
Ok, making one now :)

**Comment by Ezoteric** [comment]
:x

**Comment by whichonespink44** [comment]
Fixed in 0.5
