### ISSUE TITLE
Configurable Cave Height Limit

### ISSUE THREAD

**Issue by Muramasa-** [Team-RTG/Realistic-Terrain-Generation#337]
So from looking at RTG's config the cave frequency and density have been reduced (Now I'm assuming here) to offset RTG's extra generation time.

I'm not sure if Minecraft/RTG already has a cave height limit, but if not it could be a good option to tweak to get the right balance of cave density and frequency.

**Comment by whichonespink44** [comment]
The reduction of cave frequency/density by default was more an aesthetic decision, rather than a performance one - although faster generation is definitely a nice bonus. When the caves break through the surface at high rates, it really makes the surface look ugly.

When I was working on the caves, I didn't notice any way of controlling the heights of caves, only the frequency and density. I could probably hack together my own version of cave gen, but I think that probably goes beyond the scope of what RTG is trying to achieve.

Just to clarify, when you say "height", do you mean the max Y level at which the caves can break through the surface? Or do you mean the number of blocks from cave floor to cave ceiling?

**Comment by Muramasa-** [comment]
When I say height, I mean the maximum Y level that a cave can be generated in stone.

Thanks for the explanation, it was just if it wasn't hard to implement. But if course my assumption that it would increase performance and/or give a performance benefit when combining it with increasing cave feq and density is based on no facts.

**Comment by whichonespink44** [comment]
It's all good - I'll look into it next time I find myself in the cave code again. If there's an opportunity there to do something, I'll definitely see what I can do.

**Comment by whichonespink44** [comment]
After thinking about this in more detail, I think these kinds of 'mountainous caves' are a bit outside the scope of RTG, although I'd love to see an addon mod for this. "RTG: Mountain Caves" anyone?
