### ISSUE TITLE
Cut off trees with RTG 0.4.0

### ISSUE THREAD

**Issue by Haggle1996** [Team-RTG/Realistic-Terrain-Generation#356]
You had asked for some more information regarding trees getting cut off at borders. Here's a couple more screen shots of vanilla trees getting cut off (BigTrees trees frequently get cut off), as well as the fml-client-latest.log

https://gist.githubusercontent.com/Haggle1996/0c493a551db1bdcb5e8b/raw/a0093f1bc64425c5edc45a79903c1a3a0bd11c01/gistfile1.txt

![2015-12-21_16 57 33](https://cloud.githubusercontent.com/assets/11808184/11944644/e04f17fc-a804-11e5-8301-6578b5b98940.png)
![2015-12-21_16 57 19](https://cloud.githubusercontent.com/assets/11808184/11944647/e81f97b8-a804-11e5-8203-5129ceecaea6.png)

Some cut off hills, too:

![2015-12-21_17 05 45](https://cloud.githubusercontent.com/assets/11808184/11944696/24e2d264-a805-11e5-9c21-1eace1706caf.png)

**Comment by whichonespink44** [comment]
After looking into this in more detail, I fear that it's an unresolvable issue related to the way RTG chooses its biomes. Not so much the trees getting cut off as the abrupt transitions, like in the last screenshot you posted. I suspect the cut-off trees is only RTG's fault when the biome selection process falls apart.

Fortunately, the 0.5.0 update will likely resolve both of these issues as we're in the process of re-writing the way RTG chooses its biomes to be more like vanilla. We're hoping to release 0.5.0 on Sunday, but due to it being Xmas this week, it may get pushed back until the week after.

**Comment by Haggle1996** [comment]
Um....no Christmas presents until you release the mod? A mod pack maker can hope. :D

Happy holidays to all of you and yours, regardless. Thanks for all your hard work.

**Comment by Haggle1996** [comment]
A user of my pack reported this one last night. It's more of the same stuff, but I thought it would give you a chuckle: http://imgur.com/a/GbmO3

**Comment by Haggle1996** [comment]
I'm voting to close this issue; since 0.5.0-snapshot 4 I've not seen any cut off chunks or trees over a dozen-plus test world, other than on a couple of test worlds originally created with 0.4.0 and then upgraded to 0.5.0 with Climate Control -- and those chunk oddities are expected. I was pleasantly surprised to see I could load a 0.4.0 world with the new code.

**Comment by whichonespink44** [comment]
Yep, sounds like it's specific only to RTG layouts which we'll be removing very soon.

Thanks for all of your help with this one @Haggle1996 - much appreciated.
