### ISSUE TITLE
Can't compile latest source

### ISSUE THREAD

**Issue by Adaptivity** [Team-RTG/Realistic-Terrain-Generation#373]
Few issue about latest source code:
1) You have Enhanced Biomes assets in the repository (https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/master/src/api/resources/assets/enhancedbiomes) I think it's just an oversight.
2) EBAPI.java located in the main code (https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/master/src/main/java/enhancedbiomes/api) intentional?
3) I can't build latest source code using gradle build command. Getting an error here: https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/api/java/enhancedbiomes/helpers/ColorizerFoliageBirch.java#L5 (Can't find ColorizerFoliage)

**Comment by whichonespink44** [comment]
Yeah, the Enhanced Biomes assets are included to allow the EB textures to render when testing in a dev environment, and the EBAPI.java file is in the main code because it's not actually EB's official API (it doesn't have one) - it's just a file I wrote myself.

As for not being able to compile the latest version... hmm... I just compiled successfully here, so maybe try running `gradlew setupDecompWorkspace' and/or 'gradlew clean' and seeing if that helps.

Let me know if not.

**Comment by Adaptivity** [comment]
I usually can build any mod with just "gradle build" command. But after using gradlew setupDecompWorkspace I can compile it successfully again. I think it's mostly EB api problem. Thanks. About EB assets: maybe you can just add them to .gitignore so they won't be uploaded to repository but still be available in your dev environment?

**Comment by whichonespink44** [comment]
Glad you got it working - and good idea about adding the assets to .gitignore :+1:
