### ISSUE TITLE
Add config option to disable BOP quicksand generation

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#377]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1025

**Comment by whichonespink44** [comment]
Just some notes on this. There are only two ways we could do this (as far as I can see)...

1. We let the quicksand generate, and then replace it with something else (expensive)
2. We manually decorate all of the BOP biomes in which quicksand generates (better performance-wise, but might be time-intensive depending on how many quicksandy biomes there are).

**Comment by srs-bsns** [comment]
Since BoP does it's own decoration, can't quicksand just be turned off in the BoP configs? I've never actually looked into that before.

**Comment by whichonespink44** [comment]
I don't think the config option to disable quicksand was added until the 1.8.9 version of BOP... there's nothing in the 1.7.1 configs anyway.

**Comment by srs-bsns** [comment]
Yeah, I'm not seeing one, but I swear BoP for 1.6.4 had an option to turn it off.. it was in with the options to turn off stalactites/stalagmites, but I know the stalactites/stalagmites options were removed (but that's because the blocks were).

Hrm.. I'm not sure anything should be done about it. I can understand people not wanting quicksand in their world (I'm not a big fan of it) but this is a BoP issue. (and they won't be fixing it.) The thing is, it's just a huge waste of CPU time to let BoP place it all, only for us to then remove it. I'd just leave as is, and in a few months everyone's going to be all up in 1.9 and won't care.

**Comment by srs-bsns** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-for-1.6/src/main/java/biomesoplenty/configuration/BOPConfigurationTerrainGen.java#L136

I had to look it up just to prove that I wasn't dreaming it. :P

**Comment by whichonespink44** [comment]
Heh, seems odd they removed it for 1.7.10, and then re-added it in 1.8.9+

Having thought about it more, I'm kinda leaning towards closing this one as it's not really RTG's job to remove unwanted blocks (even though it already kinda does that very thing by adding mixed blocks to surfaces and disabling ores, etc.)

If we knew which biomes quicksand generated in, we could avoid the BOP-adds-RTG-removes approach and manually decorate those biomes to bypass BOP's decorate() method altogether. But if there are more than 3 biomes, it's probably longer than I'm willing to spend on it, especially considering that we might not be able to adequately decorate the biome given the limited access to decoration we have via the BOP API.

**Comment by Zeno410** [comment]
Yes, not our job.

**Comment by whichonespink44** [comment]
3 strikes... it's out!!! :baseball:

**Comment by forrester-marc** [comment]
You can remove quicksand from your 1.7.10 world after generation using Progressive World Cleanup https://mods.curse.com/mc-mods/minecraft/246228-progressive-world-cleanup
