### ISSUE TITLE
Option to limit world size

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#389]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1080

**Comment by Razorskills** [comment]
Does this mean a world border system similar to how FTB Utilities(http://minecraft.curseforge.com/projects/ftb-utilities) does the world border? Or more of a Endless ocean past a certain range?

**Comment by whichonespink44** [comment]
I think more of a world border type of thing. This might actually be outside the scope of what RTG is trying to do, but it won't hurt to look into it.

**Comment by Razorskills** [comment]
The reason I was wondering about an endless ocean "border" is because then someone could use that to nicely end world generation. Set the range for land generation, then a server owner could use another world border mod or system to limit the player from going out into the ocean too far. but leave enough room to use boats, or the Archimedes ships mod for travel! But that is just an idea, do what you want!

**Comment by whichonespink44** [comment]
This is outside the scope of RTG. [Climate Control](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294659-climate-control-change-climate-zones-sizes-ocean) is probably the closest you can get to this sort of thing, unless there's a world border mod for Forge?
