### ISSUE TITLE
RTG+CC crash on fresh install

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#437]
https://gist.github.com/whichonespink44/ff363fe062395fc9ebed

Setting `VanillaBiomesOn=true` seemed to fix it, which is a bit odd because having it set to false when used with other biome mods didn't stop them from generating.

**Comment by Zeno410** [comment]
This is making me suspect file problems. I have a mac and the file structure is different for window and linux.

**Comment by whichonespink44** [comment]
So if you load RTG + CC without any existing configs, you don't get the crash?

**Comment by Zeno410** [comment]
No, if you load it *with* existing configs, you don't get a crash. The problem is that the native biome check runs as soon as CC sets up its configs, but that's before EB has run at all (loading order) so the directory hasn't been created and boom. I don't think it *needs* to run then so I'll just take out the crash. I actually didn't mean to leave it.

**Comment by Zeno410** [comment]
It's the business about vanillaBiomeOn not making a difference that's making me suspicious.

**Comment by whichonespink44** [comment]
Sorry, it might be working after all... during my testing of land vs water spawns, I recorded several vanilla biome 'names' but looking at the spreadsheet again, they weren't actually vanilla biomes... for example, Birch Forest and Savanna from EBXL (those are EBXL biomes) and the Mesa is from Highlands. Doh!

Anyway, let me know when you've taken out the crash and I'll close this one.
