### ISSUE TITLE
[SUGGESTION] Ridiculous World support

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#447]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2152723-ridiculous-world-for-those-who-like-their-biomes

This is a rather small and obscure biome-adding mod by the same guy who did Forbidden Magic.

**Comment by whichonespink44** [comment]
This has already been requested in #236 - but it's funny that you should post this because I was just pondering which mod to add support for next and was just looking at their thread.

The way RTG adds support for new biome-adding mods is changing starting from v0.5.0 (basically, we're going to try to get the biome-adding mods to add support for RTG and not the other way around), so I'll approach SpitefulFox when the system's ready and see if he'd be up for it. If not, don't worry - we can still add support through RTG if necessary.
