### ISSUE TITLE
Support with AoA (Advent of Ascension)

### ISSUE THREAD

**Issue by Zottelchen** [Team-RTG/Realistic-Terrain-Generation#462]
Hi,
I'd like to request support with AoA.
Right now the game crashes with "java.lang.RuntimeException: No realistic version of biome". (see the full log [here](https://gist.github.com/Zottelchen/0a82c4faab935d603fa1))

Thank you very much.

**Comment by Zottelchen** [comment]
Oh and here is the Link to their forum topic: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286381-aoa-21-new-dimensions-330-mobs-27-bosses-skills

**Comment by whichonespink44** [comment]
This is likely a biome ID conflict of some sort.

Would you be able to post your config folder and an NEI biome dump please?

**Comment by srs-bsns** [comment]
@Zottelchen, considering all of the biome mods you are using (BoP + EBXL + Highlands), you most certainly would have had to modify the biome IDs from the defaults to avoid conflicts. If you haven't, then it's as @whichonespink44 said, probably a conflict.

Otherwise, you should first try updating to the latest [Climate Control Beta 39](https://www.dropbox.com/s/q0vo7477x4vk7wf/ClimateControl-0.4.beta39.jar?dl=0) which fixed an issue with non-default biome IDs.

If you still have this issue, then a dump of biome IDs would be helpful. If you don't know how to do that, here's how:
1. Go into the NEI options by clicking the [options] button in the inventory screen (bottom left)
2. Tools -> Data Dumps
3. There should be 2 buttons beside Biomes. Click 'Used' until it says 'All' then click 'Dump'. This will create the file /dumps/biome.csv in your minecraft directory, which is just a text file. Paste this to pastebin.

**Comment by SOL3675** [comment]
I have some info about AoA compatibility.
I'm making new my modpack recently, and works well.
I tried these patterns below.
RTG v0.4.0 + AoA + the others
RTG v0.5.0 + CC + AoA + the others
RTG v0.6.0 + CC + AoA + the others
I'm using about 200mods but I have no problem with avoiding ID conflicts.

**Comment by whichonespink44** [comment]
Thanks guys - closing this as it's almost certainly related to an ID conflict of some sort.
