### ISSUE TITLE
Oil of BuildCraft - generated

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#475]
I disabled generation Oil ine the BuildCraft and RTG configs, but it still generated.

![2016-02-04_17 31 04](https://cloud.githubusercontent.com/assets/6783568/12819870/8174e228-cb65-11e5-8e4f-9a1a243cfd24.png)

**Comment by whichonespink44** [comment]
BuildCraft generates both oil springs and oil biomes. To prevent oil springs from generating, you need to set **spawnOilSprings=false** in BuildCraft's main.cfg

Let us know if that doesn't work & I'll re-open the issue.

**Comment by srs-bsns** [comment]
I'm assuming, based on the other issue that you've submitted (https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/474), that the same mods are being used from that crash report.

This issue is likely PneumaticCraft generating that oil. Oil is an integral part of PneumaticCraft now, and if BuildCraft in present it generates pools of BC oil instead so you don't have 2 types of oil in the world.

I performed two tests
1. BC with world gen turned off, without PneumaticCraft present.
2. BC with world gen turned off, PneumaticCraft present with D:oil_generation_chance=75.0 (increased from 15.0)

In the first test there wasn't any oil pools that I could see. In the second test there were pools of BC oil everywhere.
