### ISSUE TITLE
Exception ticking world (RTG + CC + BOP)

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#514]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1661

https://paste.ee/p/sEsA3

Looks like it's trying to decorate a vanilla Ice Plains biome, but for some reason BOP is getting involved. Maybe it's got something to do with BOP's 'override vanilla biomes' config options?

**Comment by whichonespink44** [comment]
IHaTeD2 has [confirmed](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1663) that he was using default configs, so I'll try to reproduce this with a minimal setup.

**Comment by whichonespink44** [comment]
So far, I've been unable to reproduce this using:

RTG 0.6.2 (default configs)
CC 0.5.beta45 (default configs + disabling Origin Valley)
BOP 2.1.0.1548 (default configs + disabling Origin Valley)

World seed from crash report:
-2322619256059992712

Teleporting to x=1569.03, y=67.00, z=2843.53 as per the crash report and flying around a 500-ish-block radius.

Also tried the same setup above, but with OptiFine_1.7.10_HD_U_C1 and still no crash.

**Comment by srs-bsns** [comment]
I did a few tests for this some hours ago, using settings that made the worlds mostly snow biomes and mostly vanilla ice plains, and was unable to reproduce this crash either. In one world I manually generated about 100 regions.. nothing.

Without using the specific biome adding mods with specific biome IDs settings that IHaTeD2 used, it's unlikely we'll be able to reproduce the same world that he had. Even using 'defaults', if he was using old config files with default settings it could be different than what we'd get because of mods that automatically adjust their biome IDs, like ExtraBiomesXL and AE2.

**Comment by whichonespink44** [comment]
Yeah, it's probably a biome ID conflict of some sort because BOP shouldn't be getting involved with vanilla biome decoration. Either that, or some other mod is interfering with decoration or chunk loading somehow. In fact, I wouldn't rule out Optifine being the culprit as there are quite a few settings in there that modify the way chunks load.

Either way, I totally agree that unless we get the exact environment IHaTeD2 was using, there's no point in spending any more time trying to reproduce this.
