### ISSUE TITLE
Deep oceans too noisy for 1.8

### ISSUE THREAD

**Issue by topisani** [Team-RTG/Realistic-Terrain-Generation#527]
this is not a big issue in 1.7, but in 1.8... i think ill just show you:
![2016-02-21_18 49 52](https://cloud.githubusercontent.com/assets/3133596/13204355/4308c862-d8ce-11e5-9c07-f0ab7163a11e.png)
![2016-02-21_18 53 10](https://cloud.githubusercontent.com/assets/3133596/13204356/472bc336-d8ce-11e5-8b1f-6a1c7fb2d4a6.png)
Both are deep ocean biomes, and both of them look a bit extreme
I propose decreesing the noise dramatically for deep oceans, and then letting them sit around 30 - 35, with normal oceans being much more shallow.
I could make this change for 1.8 only, but i also think it would look better anyway.

**Comment by Zeno410** [comment]
Not really seeing the problem - so sometimes monuments are buried and sometime they aren't?

**Comment by topisani** [comment]
Yep and they don't look very good when they are buried, cause the border is quite hard

**Comment by whichonespink44** [comment]
I'm fine with buried Ocean Monuments - it happens all the time with Desert Temples because of RTG's elevated terrain. But obviously, if it can be avoided, then let's do it, but... there are issues with lowering the ocean floor (it affects neighbouring biomes by 'pulling them down' and messes with the biome/beach repair systems), so we should be looking at other solutions.

Either way, I think we should keep 1.8 issues out of this issue tracker, so I'm going to close this here and re-create it over on the 1.8 tracker.

**Comment by Zeno410** [comment]
*Deep* oceans don't often affect land, so you can move them up and down without too much trouble
