### ISSUE TITLE
Add some decoration to fallen trees.

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#576]
Leaves, mushrooms, etc:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1946

**Comment by Zeno410** [comment]
We do get mushrooms sometimes with BoP+Pam's. Leaves I actually we shouldn't because on real trees they're dead in days while the logs can lie around for years. In true wild forests, fallen trees and logs are fairly common and they actually generally don't have obvious stuff growing on them. It's only human manicuring and scavenging that makes them rare.

**Comment by whichonespink44** [comment]
The fallen trees in RTG already have the ability to have leaves at the end of them, but I wasn't a fan of the aesthetic it created, so I never used it. However, I can see how other might disagree, so maybe the leaves should be a config option, disabled by default. Maybe the option could even be frequency-based, so instead of just saying leaves or no leaves, the user could choose a random chance value, similar to the way we do cobblestone boulders.

Not sure how I feel about RTG adding mushrooms and other decorations to the logs... 'less is more' in many cases, and I think this is probably one of them.
