### ISSUE TITLE
Config Overhaul

### ISSUE THREAD

**Issue by topisani** [Team-RTG/Realistic-Terrain-Generation#589]
- [ ] Per-world configs
- [ ] Config GUIS
- [ ] Better BiomeConfig system

**Comment by Zeno410** [comment]
Here's file using my worldspecificconfig system: https://github.com/Zeno410/Climate-Control/blob/master/src/climateControl/api/ClimateControlSettings.java

It's pretty complicated because it has sub-configs and so has to override the default behaviors of a setting object to read and write from a config object or to DataInput/Output.

Here's another which uses a subclass providing some groupings for biome configs:
https://github.com/Zeno410/Climate-Control/blob/master/src/climateControl/biomeSettings/BoPSettings.java

So in this you just define an "Element" field and it will put ID/climate/incidence/village config parameters into the appropriate parts of the config file

**Comment by topisani** [comment]
I guess we can close this since most of this seems to be v2 stuff
