### ISSUE TITLE
TC Cinderpearls not spawning in deserts

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#618]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2264

I'm sure I've seen these before, but no harm in double-checking.

**Comment by Zeno410** [comment]
I've seen them too, but it's been a while since I looked.

**Comment by srs-bsns** [comment]
I'm not sure if this is on BoP's side, or Thaumcraft's, but cinderpearls don't seem to generate in BoP biomes, but they do just fine in vanilla biomes.

I'll test later with other biomes mods, and if the same thing happens then the bug is likely Thaumcrafts, otherwise it's BoP's, but in either case it doesn't matter, because neither mod is likely to be updated to fix this.

Another test to do is Thaumcraft and BoP without RTG, but it's unlikely that will change anything.
