### ISSUE TITLE
Strange cliff in BOP Ominous Woods

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#621]
Not sure what's happened here, but it looks like the noise spiked a bit and kickstarted the CliffCalculator:

![bop-ominous-woods](https://cloud.githubusercontent.com/assets/10927161/14404739/83052c72-fe75-11e5-8a21-e392208cb33b.png)

**Comment by Zeno410** [comment]
I saw something like this once. It seemed to have been a rounding error caused by a noise with a wavelength close to a chunk multiple.

**Comment by Zeno410** [comment]
I made a change to hills() which will fix this instance but I don't know if it will fix the overall problem.  It's quite rare. Unfortunately this will cause detail changes although not character changes to all sorts of biomes.

**Comment by whichonespink44** [comment]
Personally, I think it looks pretty cool, but just wanted to post it in case it was a sign of an underlying issue. If it's that rare (and the hills tweak might fix it anyway), I think we can probably close this one. But I'll leave it open for now if you want to look into it.

**Comment by Zeno410** [comment]
It's not cool, trust me. It looks hideous in-game. I'm actually less sure about the cause because this came up with the fix I'd done for the time I ran into it before. The current change is almost throwing spaghetti against the wall to see if it sticks, but it's a good change in general (making 2 different noises use different octaves).

Because it's dependent on some rare confluence of events (I know that even if I don't know the events), basically any change should fix *that* particular incidence.

**Comment by whichonespink44** [comment]
Closing this as it's likely been fixed in 0.8.0-snapshot-3 but we can always re-open if it appears again.
