### ISSUE TITLE
Biome conversion of lakes.

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#663]
Scenic lakes are not generating water plants, probably because they're not usually water biomes (sometimes they get converted to ocean or river, which is really not correct but hard to fix). I could convert them to water biomes, I think, without too much in the way of side effects. However, there's the question of what to convert them to, since there's no Lake in vanilla, or for that matter in BoP or EBXL. I could convert them to Lake if EB or Highlands is going, and otherwise convert them to River or Ocean. 

There's also the issue of snowy biomes - Lake is probably wrong, so should that go to Frozen River or Frozen Ocean?

Reference: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2436

**Comment by topisani** [comment]
long term, what is the solution to this? i mean, in v2, if terrainfeatures turn out as i plan them to do, lakes will be terrainfeatures, and their biome can be set without any use of biome repair or stuff like that, so it will be 100% foolproof. But other than that im thinking river, since those probably have the most fitting decorations. We dont want coral reefs or ocean monuments (bad examples since they never would spawn there, but you get what i mean) in our lakes, but we would want all the stuff people put in rivers

**Comment by Zeno410** [comment]
I'll bet there are some mods that would spawn ocean decos there at least, so that's pretty much a slam dunk not to go to Ocean when it can be stopped.

**Comment by whichonespink44** [comment]
I'm definitely thinking River / Frozen River for everything in the short term. However, maybe we could look at doing a config option to let users choose what they want? Something like:

`I:"Biome ID to use for RTG scenic lakes"=7`
`I:"Biome ID to use for RTG scenic frozen lakes"=11`

And then maybe setting either of those two config options to **-1** would use whatever biome the lake happened to generate in, for those users who don't want any special decorations in their lakes?

**Comment by whichonespink44** [comment]
Added in d1e9bea.
