### ISSUE TITLE
Update AbyssalCraft API

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#671]
https://github.com/Shinoow/AbyssalCraft/commit/75de4a50c72803b6d65df239dc755f3572a9a0f4

**Comment by whichonespink44** [comment]
Srs said:

> we can change the dep string from "after:abyssalcraft@[1.8.9.6,)" to "after:AbyssalCraftAPI@[1.6,1.7]"

**Comment by Shinoow** [comment]
Might wanna set it to API 1.7 (since that's where the biome part is implemented). Alternatively, you can specify AbyssalCraft version 1.9.1.2. I'm probably going to re-brand the API name back to naming all packages `AbyssalCraftAPI` in the 1.8.9 and 1.9 branch, so staying with mod version will ensure compatibility in those branches when I do the re-branding.

**Comment by whichonespink44** [comment]
Updated in 21478f4

Went with the `abyssalcraft@[1.9.1.2,)` as it provided a slightly more user-friendly warning message.

@Shinoow See you in 1.9 very soon!! :dancer:
