### ISSUE TITLE
Volcano surfaces

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#729]
![volcano](https://cloud.githubusercontent.com/assets/10927161/15605899/c7659090-2400-11e6-8be4-2ecc1b5c32d4.jpg)

Now that volcanoes are working again, it would be nice to put some finishing touches on them, specifically with regards to their surfaces.

I personally think they should look like the image above, with the host biome's surface creeping up the foot of the volcano, blending them into their surroundings. I also think we need to add at least one mix block into the mix - probably coal block since it's black and kinda 'makes sense' (ish).

But this is just *my* dream volcano... happy to consider other ideas - just be sure to post an image for reference so we're all on the same page.

**Comment by topisani** [comment]
post YOUR dream volcano below!

**Comment by VelocityRa** [comment]
Right, I'll give Volcanoes some more love in the following days. 
I'm liking the idea of the coal block as a mix block, gonna have to see it in action. I'm gonna need a list of possible mix blocks, other ideas? There's stained clay, but what colors would look good?
Here's a pretty similar picture to @whichonespink44's that would be a good example to shoot for I think.
![](http://www.placestoseeinyourlifetime.com/wp-content/uploads/2013/10/mayon.jpg)

**Comment by Zeno410** [comment]
![image](https://cloud.githubusercontent.com/assets/5322776/15624047/dd20024e-2432-11e6-861e-82ccafdd12a9.png)

**Comment by HyperionNexus** [comment]
[http://img.turtlehurtled.com/volcanic-eruptions1/klyuchevskaya-sopka-4.jpeg](url)

**Comment by srs-bsns** [comment]
>@whichonespink44
>probably coal block since it's black and kinda 'makes sense' (ish).

>@VelocityRa 
>I'm liking the idea of the coal block as a mix block,

I'm not liking the idea of using a resource block for world decoration. Though coal is usually the most abundant resource making it less of a deal, using it in that manner would kind of put the game out of balance for anyone that comes across a volcano. And, I can totally picture people strip mining the coal away and leaving a ruined landscape behind.

Furthermore, it would be a problem for people that create worlds that don't generate any resources in them (using Ex Nihilio, et al., instead), such as a survival island type modpack (with a volcano on it, of course.)

I'd suggest black stained clay, but stained clay doen't look rough enough.

I can think of a lot of blocks added by other mods that would be great for this (UBC, ExUtils stained cobble, basalt added by various mods), but nothing Vanilla... THANKS MOJANG FOR THE AWESOME VARIETY! :unamused:

The best solution for this specific problem on it's own would be to just add custom blocks, but that's the worst solution overall because it would mean that RTG would no longer be server-side only.

**Comment by VelocityRa** [comment]
@srs-bsns Yeah that's a good point, about the coal blocks.
@Team-RTG/everyone And I'm all up for adding custom blocks, I think RTG beeing server-side only is way too limiting (just imagine the possibilities...).
The modpacks that use RTG can just include it in their client (most do anyways) and I don't think it's worth it at all to keep it server-side. If people are gonna use RTG, they're gonna have it in their modded client. Those that don't, are a huge minority, why should the rest (most) get a lesser experience? One of the reasons I got into modding and not server plugin development was that complete freedom you just can't get with the latter. But with RTG we can't have that currently.

I never suggested dropping server-side only support though because I know there's a scope we have to comply with. I'd be willing to "expand" it, mind you, but the people working on this longer than me (which is everyone else in this team), probably see things differently.
I'd love to be proven wrong.

**Comment by whichonespink44** [comment]
For me, it's not so much about keeping RTG server-side only as it is about keeping RTG's scope as narrow as possible. The 'server-side-only' thing just happens to be a good 'compass' for keeping the  scope in check.

I'm all for expanding RTG, but let's do it through addons. In fact, maybe we should make volcanoes an addon. It would allow us to add custom blocks and design the volcanoes exactly as we want. We could even have multiple surface styles to choose from, and maybe even different shape designs if we wanted to go down that route.

**Comment by chaNcharge** [comment]
![msh82_st_helens_plume_from_harrys_ridge_05-19-82](https://cloud.githubusercontent.com/assets/11594018/15625528/5042f8c8-245e-11e6-9468-bffa0fc22211.jpg)
We could have a volcano like this, life you said, different styles of volcanoes, composite, shield (like how it is currently), and cinder cones. You could also try making it so the volcanoes actually erupt from time to time, that would be really cool!

**Comment by whichonespink44** [comment]
It we did Volcanoes as an addon, animated eruptions could certainly be a thing (in theory anyway).

**Comment by VelocityRa** [comment]
Sound good to me. It could still be included in the main mod and just be active only when running on the client. (The problem to solve there would be, what would we do from a servers perspective, generate a server-friendly RTG world, or one in which people need the client)
That might just be my reluctance to have more .jars though (I never liked mods that did that). If it *has* to be a a .jar, just 1 seperate addon that added *all* client side stuff would perhaps be preferable.
@chaNcharge Creating that kind of volcano would require a lot of changes, so I'm not sure it'd be worth it for 1.7.10. Let's just nail "normal" volcanoes and be done with for that version.
All this talk about a client addon is for 1.9, right?

**Comment by topisani** [comment]
i 100% agree on RTG having to be server side only. For 2 reasons: as pink said its a good way to keep the scope narrow, but another thing is, in 1.8+ vanilla clients can connect to forge servers if the server has no mods that are required on the server. We are currently mentioning this absolutely nowhere, but it means that people using just a vanilla server, or even spongeforge, could use RTG! and that is an awesome quality noone else has.  

 I also think, if we add bigger client stuff (like blocks and such, IMO custom fog and such would be acceptible in the main jar, as long as it is not required) it has to go into its own jar. No, i also dont like mods splitting across jars, but i think a volcano addon would be fine.

**Comment by Zeno410** [comment]
Given that typical modpacks have over 100 jars, I don't see an issue with multiple jars. I was also about to mention topi's point that being serverside only means you can use it on servers for vanilla worlds, which is an incredible feature, but he beat me to it.

**Comment by VelocityRa** [comment]
@topisani Yeah I think your 2nd point is reasonable; coupled with the idea of an addon for client stuff it could solve both issues. Also glad you agree on integrating some client stuff in the main RTG jar. Dropping server-side only support when a middle solution is possible was unreasonable of me to suggest.
> in 1.8+ vanilla clients can connect to forge servers if the server has no mods that are required on the server.

We should really mention this feature somewhere though...

**Comment by RufusStark** [comment]
Just an idea... would it be possible to have a whitelist of blocks added by other mods in the config file. Have a reasonable default setting for very common mods, and check which ones are available during post-init. Would that work? 

Also, Railcraft's Abyssal stone/cobblestone would be good choices. I think it would look good and makes some "geological sense".

**Comment by srs-bsns** [comment]
@RufusStark, This isn't an issue of mod-added blocks, of which there are several good choices from several different mods. There needs to be a solid default based on vanilla blocks, and that's the issue. Vanilla Minecraft has a shit selection of blocks that are appropriate for volcanos.

**Comment by Ezoteric** [comment]
Well coal blocks are nice and the hardenend clay, its just the coal blocks makes it OP for resources.

**Comment by RufusStark** [comment]
@srs-bsns - Right, I get that. I guess I was just assuming that the vast majority of the time those other mods will be there, and when they're not, just don't use another block to mix in. I see the point of having an alternate block in vanilla + rtg situations, though. But if volcanos are moved into an add-on so that a block can be added, then it seems to defeat that purpose to me. That said, it's just my opinion and I don't want to give the impression that I think it carries any (particular) weight.

On a side note, I found seven or eight volcanos all right near each other (a few kilometers?) in a world I created yesterday while testing for the ConcurrentModificationException issue. Weirder still, a village spawned partly on the side of one of them, but unfortunately it didn't suffer a Pompeiian fate. I was kind of looking forward to seeing that in action.

**Comment by Zeno410** [comment]
I think we could write the configs to take block names for the surfacing block (like undergroundbiomes:igneousStone:5 for UBC Basalt), with either an error or a default if the name isn't valid.

**Comment by whichonespink44** [comment]
There's already a [config option](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/etc/config/RTG/rtg.cfg#L365-L371) for the volcano block, but not sure how that's going to work if we start using more than one block for the surface. I suppose we could make each block configurable.

**Comment by whichonespink44** [comment]
@VelocityRa I'm happy to leave this until after 1.0 is released, but if you want to try to get it in before, go for it.

**Comment by whichonespink44** [comment]
Moved this back into the 1.0 milestone as it's nearly finished based on what @VelocityRa's been working on recently.

**Comment by whichonespink44** [comment]
Finished in c20823e

![](https://cdn.discordapp.com/attachments/168326116761665536/191241860436459521/2016-06-11_20.25.58.png)
