### ISSUE TITLE
[1.8.9] Fix uppercase namespace in resource dir

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#772]
_From @srs-bsns on April 7, 2016 4:46_

src/main/resources/assets/RTG/ <---toLower()

_Copied from original issue: Team-RTG/1.8.9-Realistic-Terrain-Generation#66_

**Comment by srs-bsns** [comment]
I was going to close this, but realised after checking that it is still an issue in the 1.8.9 branches.
How did we fix it in the others but not here?
We REALLY showed a lack of love for 1.8.9 :o

**Comment by whichonespink44** [comment]
Yeah, I'm gonna try to re-visit 1.8.9 every so often, doing bits and bobs from the issue tracker when I can.

I had originally wanted to try re-porting it from 1.7.10, but... that's just not going to happen with 1.9.4 in full throttle now. Also, I think the general consensus was that it would be better to backport 1.9.4, but... we're a long way away from a stable 1.9.4 beta if the plan is to port all the latest 1.7.10 stuff into 1.9.4, so... it looks like 1.8.9 is hardly gonna get any love for a while.

Poor 1.8.9 :disappointed:

**Comment by Oxosorrel** [comment]
1.9.4 ???! That's so old now. 1.10.2 or bust. </sarcasm>

**Comment by Oxosorrel** [comment]
I dropped my sarcasm tag. However in all seriousness. With 1.10.2 out, I have my doubts that 1.9.4 will ever be called officially "stable".

**Comment by srs-bsns** [comment]
@whichonespink44

On one hand, with the amount of porting that needs to be done to get the 1.8.9 version up-to-date with all of the changes made to 1.7.10 since Topi updated, it would probably be easier to just re-port from 1.7.10 in it's current state.

On the other hand, even if we got 1.9.4 into a semi-decent state, it's kind of late to back-port now. Too much effort to do and maintain for likely only a small number of people as most people likely won't be creating a new world in 1.8.9.

Poor 1.8.9 :skull:

@Oxosorrel, ATM, there is a recommended version of Forge for 1.9.4, therefore 1.9.4 **is** _officially_ 'stable'. Also, there aren't any changes in the, currently unstable, Forge 1.10.2 codebase from 1.9.4 that affect RTG, so RTG for 1.9.4 will work just fine with Minecraft/Forge 1.10.2. For that reason, there's no point in not staying with Forge recommended (1.9.4-12.17.0.1976) for now.

**Comment by Oxosorrel** [comment]
@srs-bsns would you look at that... I stand corrected. 1.9.4 must have very recently been promoted to recommended. Not but two weeks ago I was begging another Mod author to update 1.9 to 1.9.4, and they were adamant about staying on the recommended version, and I had given up hope on seeing that happen when 1.10 released. 

Since RTG will be happy in 1.10.2, then I'm a happy RTG user!.

**Comment by whichonespink44** [comment]
Fixed in d497eb6
