### ISSUE TITLE
Server crash with apparently no reason

### ISSUE THREAD

**Issue by lightning02** [Team-RTG/Realistic-Terrain-Generation#832]
http://pastebin.com/uR1EHdVh
The latest log: https://www.dropbox.com/s/jhwodjyr2jck9ba/2016-07-14-3.log.gz?dl=1

**Comment by whichonespink44** [comment]
Hi @lightning02 

Sorry, but we don't support Thermos/Cauldron/KCauldron /Craftbukkit/Bukkit/etc.

I'm closing this, but if you can reproduce this crash in a Forge-only environment, we'll re-open and investigate further.

**Comment by srs-bsns** [comment]
@lightning02, This appears to be identical to an issue that we just fixed in our event manager. Try updating to [RTG-1.7.10-1.1.0-snapshot-1](https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/download/v1.7.10-1.1.0-snapshot-1/RTG-1.7.10-1.1.0-snapshot-1.jar)

### Note that this is a SNAPSHOT version, so you should make a back-up of your world before using.

**Comment by lightning02** [comment]
Tryng to reproduce on forge would be painful and would take alot of time since this is a random crash, also, Robotia and other Thermos developers are really kind and open, I guess they would not reject further investigation and help other mod developers to fix any possible issue (if asked to them). 
@srs-bsns thanks alot to have at least looked into the logs, I really appriciate, I will try this snapshot with a backup and see if the crash will still occur in the next days :)

**Comment by lightning02** [comment]
I reopened this at #833
