### ISSUE TITLE
Faked biomes not adhering to I:"Number of flat bedrock layers"

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#842]
May possibly be indicitive of some other issue.

**Comment by topisani** [comment]
this is intentional. The faked biomes have bedrock as part of what we would call surfacing, and i dont want to also be placing our bedrock in there, as the randomnes would probably be affected quite a bit by that. We could do a bigger workaround, but personally i see very few uses for that config option anyway, and prioritize the simplicity of the faked biome system.
