### ISSUE TITLE
Worlds sometimes do not populate biomes properly

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#870]
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version: 1614
- RTG version: 1.7.10-1.10
##### Issue Description:

(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

https://www.dropbox.com/s/v9vamoj3hpk4f0k/Screenshot%202016-07-26%2013.23.22.png?dl=0
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Create a world
##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

Due to the sheer size of my pack, I will instead use my latest file, to show any relevant mods, in case any mods are known culprits. http://pastebin.com/T9Spcc62

If files such as config files and such are needed, I will post them.

**Comment by srs-bsns** [comment]
Can you reproduce this with just RTG? Because I don't recall seeing anything like this with just RTG, nor RTG in a small mod pack.
What biome were you in when that screenshot was taken?
Also, it would be nice to see your `fml-client-latest.log` (you provided `latest.log`, which isn't much help :)

**Comment by Sunconure11** [comment]
IIRC, Snowy Coniferous Forest from BoP

**Comment by Sunconure11** [comment]
I'll install RTG first to a save, then CC, and BiomeTweaker, and finally, Biomes O' Plenty, to rule out commonly used mods.

Edit 1: Does not happen with RTG alone. but holy shit it is lagging more than normal. I'll try the additive approach and tell you when I find a mod in question that could be causing this.

Edit 2: Here is the log, in the mean time, since it is clear this is related to another mod interfering somehow. https://gist.github.com/Sunconure11/86b29e1dd4b4a0bdd5e4fad1e2545449

Edit 3: Too laggy to continue (I think I accidentally confirmed #868) via this route, I'll send you the curse profile for the next update of my pack, to see if you can investigate it. Warning: Huge, though I'm focusing a bit on removing some unused stuff or redundant stuff.

https://www.dropbox.com/s/lw1etyc52v5csmo/compitum.rar?dl=0

**Comment by Sunconure11** [comment]
Also included in there is a save that is having the issue.

**Comment by srs-bsns** [comment]
@Sunconure11
The problem with biome decorations and streams being incomplete (filled in with cobblestone) is a result of something that MagiaNaturalis-1.7.10-0.1.5b is doing.
It is, I believe, halting decoration events, but I don't know for certain because that mod is closed-source, and I don't really want to spend more time on this.

With MagiaNaturalis:
![2016-07-27_07 45 46](https://cloud.githubusercontent.com/assets/8453133/17176750/1dd630a0-53dc-11e6-9e55-f7e25f0a0ee5.png)

Without MagiaNaturalis:
![2016-07-27_09 20 11](https://cloud.githubusercontent.com/assets/8453133/17176752/2006dc8a-53dc-11e6-8f51-7977b52c754f.png)

As for..

> but holy shit it is lagging more than normal.

I'm not sure your context of 'lagging', but I can say for certain that it's not RTG causing a huge amount of lag (speed of world gen). RTG by itself or in a small modpack can generate terrain at nearly vanilla speed in some instances, and since it has no effect on the client, there shouldn't be any kind of client-side CPU/rendering issues at all from it.

When I loaded your full modpack I had some seriously low FPS and everything was sluggish because the modpack is highly dependant on CPU and other client-side stuff. As I was removing mods to find the cause of the decoration problem, performance began to improve to an acceptable level, mostly after removing the mods that add living entities, like animals. So, if you want to improve performance, you may want to start there. (Mobs have always been a cause of performance issues, atleast pre 1.8.) Also, when doing a quick performance analysis, Stellar Sky also seemed to be eating up a good portion of CPU as well.

**Comment by Sunconure11** [comment]
For some reason, on a small pack when I was trying the additive approach to get as few mods possible to cause this issue, I started lagging badly on world generation. CPU usage was getting pretty high.

I'm trying to hunt down TrinaryBrain to see if he can fix this before I pull it from my pack.

As for your tweak suggestions, I'll take them in mind. Though I've always had a hard time with the spawn rates from lycanites mobs.

**Comment by Sunconure11** [comment]
I'm not 100% convinced that it is Magia Naturalis, but I have removed it from my pack for now. (I tried to hunt down the dev via normal routes he is supposedly on, and never found him)

Out of curiosity, can you list what mods you removed, aside from Magia Naturalis? I want to look into it, since my computer has to have its motherboard replaced today, so I can have the list for reference.

But seeing as there is some derpiness currently, including with Antique Atlas, and some internal stuff, it could still be an RTG issue in some weird way. Plus sometimes this issue happens when I reload the world by logging in and out of the world, just like in #872, even after removing Magia Naturalis.

Removing Magia Naturalis helped out a bit, but I still sometimes find various errors (such as missing patches of snow in cold biomes where there should be snow) in random worlds. As well as this, upon reloading a world (exit the game entirely, then load the world again), biomes will stop decorating properly.

I will let you inspect a faulty world, since I won't be able to do so for a couple of days (mobo has to be replaced, therefore no access to my machine): https://www.dropbox.com/s/9onui2m2mcc90ly/worldforinspection.zip?dl=0

Magia Naturalis was removed, and this still happens.

**Comment by srs-bsns** [comment]
> Out of curiosity, can you list what mods you removed, aside from Magia Naturalis?

Once I discovered that it was MagiaNaturalis all mods were re-enabled except for it in order to be sure.

## 

> when I reload the world by logging in and out of the world, just like in #872

It can't be related to #872 at all because all of my testing was done in a new world each time, and #872 will only ever occur upon reloading an old world.

## 

> but I still sometimes find various errors (such as missing patches of snow in cold biomes where there should be snow) in random worlds.

There is the possibility that another mod, under different conditions, is also affecting biome decoration events in the same manner, and causing the same type of effect. I only discovered MagiaNaturalis doing it in the above situation.

## 

Until #872 is resolved, (hopefully later today), I advise that all testing be done in newly created worlds only.

**Comment by Sunconure11** [comment]
I see.

**Comment by Sunconure11** [comment]
Also, what software did you use to test Stellar Sky? I would like to give a report of such to Abastro if it hogs up CPU usage on 1.10, since we know it hogs up usage on 1.7.10.

**Comment by srs-bsns** [comment]
I don't know that Stellar Sky has high CPU usage. I didn't test it thoroughly; I just noticed high CPU usage when I performed a quick analysis, but it could have easily been an anomaly.

I used VisualVM, which is a part of the Java JDK distribution.

**Comment by Sunconure11** [comment]
Huh, it looks like this issue followed me into 1.10.2, on a sponge-based server. I'll investigate further before I request this be re-opened, or make a new issue.

**Comment by srs-bsns** [comment]
@Sunconure11

It is highly unlikely that it is due to Sponge, or any Sponge plugin. It is likely caused by a poorly coded mod (Magia Naturalis in this case for 1.7.10) doing something that it shouldn't, and posibly from a core mod.

Regardless, the cause will not be RTG, so there's no reason to revisit the issue here.

**Comment by Sunconure11** [comment]
https://pastebin.com/VV7F1KJb

If it's not RTG, then I'm curious, are any of these core mods then, known for this?
