### ISSUE TITLE
Allow decorators from other mods (such as BoP flowers) to spawn in modded biomes in RTG Worlds

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#871]
Just what it says on the tin. Grasses from BoP could spawn in EBXL biomes for instance.

**Comment by Zeno410** [comment]
Generally I think that should be a decision for the author of the mod doing decoration. Whether they want to decorate a particular biome or some combination via the biome directory, that's their choice.

**Comment by srs-bsns** [comment]
@Sunconure11 
In order for (going by your example) EBXL biomes to be decorated with BoP assets, either BoP's decoration methods would have to be altered (on their end) or, in RTG we _COULD_ override the decorations and do this ourselves, but that would be 1. outside of the scope of RTG, and 2. what Zeno said.

It might seem hypocrtical because we do some biome decorations, but it's mostly custom trees, and we only use vanilla blocks.

In any sense, there are no plans to add any new features to RTG-1.7.10, and in 1.9.4/1.10.2, atleast for the time being, BoP seems to be the only major biome mod.
