### ISSUE TITLE
1.10.2-RTG Crash w/ Streams Mod

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#882]
##### Affected Mod Versions:

Streams Mod and maybe Ore Plants Mod: 
http://minecraft.curseforge.com/projects/ore-plants
http://minecraft.curseforge.com/projects/streams
- Forge version: 12.18.1.2026
- RTG version: 2.0.0
##### Issue Description:

Crash while in the world generating new chunks
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Walk around until streams tries to generate.
##### Extra Information:

-Crashlog: http://pastebin.com/itXzZqrQ

**Comment by srs-bsns** [comment]
This looks to be most likely an issue with Streams. You should open an issue in the [Streams Repo](https://github.com/delvr/Streams/issues).
If you open an issue there, please link this issue by adding "**Team-RTG/Realistic-Terrain-Generation#882**" to your post.

Due to the nature of Issue #866, I'll keep this open until I hear back from @delvr

**Comment by Zygus42** [comment]
I'm now using the latest RTG and Streams and it's working flawlessly.
