### ISSUE TITLE
RTG 1.7.10/1.8.9: Multiple bugs

### ISSUE THREAD

**Issue by Quizer9O8** [Team-RTG/Realistic-Terrain-Generation#899]
Affected Mod Versions:
- RTG version: 1.1.1
- Biomes O' Plenty (latest version for 1.7.10/1.8.9) 
##### Issue Description:
- Bug 1: 
  ![2016-08-16_18 12 06](https://cloud.githubusercontent.com/assets/19509275/17708513/a8892eb4-63e5-11e6-9c12-28f433966f50.png)
  BOP's Marsh biome tends to create a massive load of undergrounds lakes which causes your FPS to drop down to 0 when near.
- Bug 2:
  ![2016-08-16_17 34 50](https://cloud.githubusercontent.com/assets/19509275/17708585/f0874b6a-63e5-11e6-86b4-9334abb41c2b.png)
  ![2016-08-16_17 34 51](https://cloud.githubusercontent.com/assets/19509275/17708592/f85aaea4-63e5-11e6-9bdc-cc0e400e91bb.png)
  ![2016-08-16_17 34 52](https://cloud.githubusercontent.com/assets/19509275/17708597/fdc3c4de-63e5-11e6-8d47-c840cfa3b2b8.png)
  Horses tend to be partly stuck in the terrain which causes them to suffocate.

**Comment by srs-bsns** [comment]
> BOP's Marsh biome tends to create a massive load of undergrounds lakes which causes your FPS to drop down to 0 when near.

It's unlikely this has anything to do with RTG created lakes. BoP has no affect on how RTG generates them and as far as I know we don't do anything special with lakes in BoP biomes. @whichonespink44 would know better than me though.

> Horses tend to be partly stuck in the terrain which causes them to suffocate.

This is a vanilla bug that has been known for quite a long time.

**Comment by whichonespink44** [comment]
The excessive amount of underground lakes is caused by BOP's decorations, so there isn't anything RTG can do about this. Sometimes it's possible for RTG to manually decorate a mod biome itself, but in the case of BOP's Marsh, it would be too complicated because its surface lake generation is coupled with its underground lake generation.

@Quizer9O8 If the Marsh biome is too much of a problem, the only thing we can recommend is disabling it.
