### ISSUE TITLE
Add config option to disable the World Type notification screen

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#910]
For mod pack makers who have locked down the RTG world type, it would be good to disable it so their users don't get confused since they won't be able to choose the world type anyway.

**Comment by srs-bsns** [comment]
Or modpack authors could just include `settings.rtg` which would have the same effect.

An alternative strategy would be to add a config option, such as `B:"Display WorldType Screen"` that defaults to `true`. So when a new config is created the WorldType screen will be displayed, and instead of creating `settings.rtg` so that it only displays once, have the method instead change `B:"Display WorldType Screen"` to `false`. This way it will only display once if RTG needs to create a new config file.. most modpacks will ship config files, so this would already be disabled in those cases.

**Comment by whichonespink44** [comment]
Including settings.rtg wouldn't work as there's a string that gets written inside the file that's user-specific, so even if the file is there, it won't have the user's encoded string thing (I think it writes the profile id in everything prior to 1.10.2, and then in 1.10.2 it writes the username cuz the profile wasn't available anymore (or something like that)).

Could maybe try the writing-to-config file thing instead of settings.rtg though.

**Comment by srs-bsns** [comment]
> Including settings.rtg wouldn't work as there's a string that gets written inside the file that's user-specific

Is that data actually checked against the user to determine if that screen should be shown? It seems daft to do that since the file will only exist in a single user's client anyways, so there wouldn't be a reason for the mod to check against any user-specific data. I assumed the only check that was made was that the file existed, which is all that would really need to be done. I wonder if @Adubbz had other plans for this in BoP.

> Could maybe try the writing-to-config file thing instead of settings.rtg though.

This makes the most sense, because it will be in the config file where people can see it, and we won't be cluttering up the Minecraft root with unneeded files.

**Comment by whichonespink44** [comment]
Added in ed313d4 - just went with the config option to enable/disable.

**Comment by whichonespink44** [comment]
Fixed for 1.8.9 in 58bf5e4

**Comment by whichonespink44** [comment]
Fixed for 1.7.10 in eb53169
