### ISSUE TITLE
[feature request] New realistic nether for 1.7.10

### ISSUE THREAD

**Issue by ziadbenaman** [Team-RTG/Realistic-Terrain-Generation#938]
Hello,  It will be great if you make a new realistic verison of the nether with mountains,  bigger lava lakes volcanoes and new nether strongholds and maybe more resources (gold,  iron,  coal...) with a config option to disable it for the players who prefer the old boring nether
It will be better if you make it for 1.7.10 because none of my mods have been updated (not the most important ones)

**Comment by srs-bsns** [comment]
> Hello, It will be great if you make a new realistic verison of the nether with mountains, bigger lava lakes volcanoes

Nothing about the Nether is realistic. Futhermore, this would require a great deal of work in order to implement as the size of the Nether is different. (maximum world height is only 1/2 that of the Overworld.)

## 

> and new nether strongholds and maybe more resources (gold, iron, coal...) with a config option to disable it for the players who prefer the old boring nether

Structure generation and ore generation is outside of the scope of RTG. Though we have settings for both now (in the Overworld), they are only to enable/disable them (ores), or to change the frequency of generation (villages, dungeons, strongholds, etc..), but these setting are atiquated and may be removed at some time in the future.

## 

> It will be better if you make it for 1.7.10 because none of my mods have been updated (not the most important ones)

Development of RTG is focussed primarily on 1.10.2 and features will only be backported when feasible. Something of this magnitude, however, would be unlikely to be backported as it would take way too much effort to code and maintain when the community is migrating to newer Minecraft versions.

**Comment by ziadbenaman** [comment]
Ok thank you
