### ISSUE TITLE
#Forum The problem with beaches

### ISSUE THREAD

**Issue by ziadbenaman** [Team-RTG/Realistic-Terrain-Generation#951]
Hi again,  i installed the mod (Anti-ID Conflict) ,  the game crashed many times (could'nt start the game,) 
I removed it,  enabled  debbugging,  after this i started game,  in a new save,  while walking i foud the same thing 
Screens :
![2016-09-17_02 12 41](https://cloud.githubusercontent.com/assets/16279077/18605105/cd2eb456-7c80-11e6-808d-711e0aa3342c.png)
![2016-09-17_02 13 30](https://cloud.githubusercontent.com/assets/16279077/18605160/6364f43e-7c82-11e6-8df0-cceadab77624.png)

Logs and crash :
[crash+logs.zip](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/477929/crash.logs.zip)

**Comment by ziadbenaman** [comment]
Note: sometimes i found very wide beaches with the same style

**Comment by srs-bsns** [comment]
I'm not seeing any biome ID conflict here that would cause issues with beaches. Enviromine is setting it's cave biome to it's default ID of 23, which is overwriting vanilla's JungleEdge biome, though that is improper, it shouldn't cause anything drastic to happen with beaches.

It is the cause of the crash with AntiID-Conflict. You can change the biome ID in Enviromine's cave dimension config: `config/enviromine/CaveDimension.cfg` -> `I:"Cave Biome ID"`. Set this to something between 40-126, or 168-254 (Except biome ID 207, which is being used by MoCreatures Wyvern biome).

Since RTG doesn't handle biome layouts, I'm going to have to opine that the beach issue is caused by another mod. This could _possibly_ be caused by ClimateControl, since it does biome layouts, but only @Zeno410 can comment on that at any length.

RTG has a biome repair feature that works on beaches, however, it doesn't work that high in elevation.

**Comment by ziadbenaman** [comment]
Ok thank you

**Comment by DracoScythem** [comment]
I can confirm that this happens with CC and RTG regardless of what Biome-Mods are installed.
Another notable fact is that almost all non-smoothed Biome/Chunk borders I found appeared in conjunction with this.

**Comment by ziadbenaman** [comment]
Is there any solution for this,  without removing any mod of course ?

Thanks

**Comment by Zeno410** [comment]
The crash looks like a missing biome for journeymap and I don't think CC or RTG are involved other than the specific places where the crash happens are CC driven. What's the biome on the hill?

**Comment by ziadbenaman** [comment]
The biome is beach

**Comment by ziadbenaman** [comment]
- the game was not crashing before installing Anti-ID Conflict,  the problem is the beach you see in Screens, i wanted to remove it and make all beaches look natural

**Comment by Zeno410** [comment]
We are looking at why beaches are sometimes left at elevation. No solutions so far (we don't understand how it happens). The crash, from your description, sounds like a conflict between anti-ID conflict and journeymap. Possibly anti-ID conflict is altering IDs and journeymap doesn't  know what's going on. You've got a conflict at 23 at least, so anti-ID has to be altering stuff.

**Comment by srs-bsns** [comment]
@Zeno410 I already explained the crash. Enviromine, by default, sets it's Cave biome ID to 23 (improper) which causes an obvious conflict with vanilla. This causes Anti-ID Conflict to throw a `BiomesIDConflictException`, which is the typical behavior with a biome ID conflict. This has nothing to do with the beaches, and there isn't any implication of JourneyMap.

**Comment by ziadbenaman** [comment]
Is it possible at least to change the stone blocks with sand,  it will look muck better

Thank you guys for your help

**Comment by Zeno410** [comment]
That should be doable.

**Comment by srs-bsns** [comment]
This was already discovered to be caused by CC's `B:wideBeaches=true`

**Comment by whichonespink44** [comment]
Cool, I also removed the dirt and stone in vanilla Beach in c692a04 so if it does happen again, for whatever reason, it won't look as ugly.
