### ISSUE TITLE
Add a biome option to use a default landscape.

### ISSUE THREAD

**Issue by AnvilPuncher** [Team-RTG/Realistic-Terrain-Generation#953]
Hello,

This is a wonderful mod with beautiful landscapes and there could be little to suggest for improvement.  Yet, some modded biomes are rather bland with RTG's rolling landscapes.  I'm making the suggestion that there be an option to have the more jarring cliff faces and hills so some of the more extreme and unique land generation found in some modded biomes are retained.  

Thank you

**Comment by whichonespink44** [comment]
This isn't likely to be implemented in this incarnation of RTG... there are already biome configs to use the original biome's decorations and surfaces instead of RTG's decorations and surfaces, but the terrain always needs to be RTG's terrain.

If we ever get around to finishing RTG2 (a total rewrite of RTG), this will be possible, but as it stands now, it is not.

The only thing we could do is to modify the terrain of certain biomes to more closely resemble the vanilla/modded counterparts.

@AnvilPuncher What biomes do you think need to be more like their originals? Maybe we can tweak them in a future release. Also, which version of RTG are you using?

**Comment by AnvilPuncher** [comment]
I am using 1.7.10-1.1.1 and the biomes that I was referring to are from Highlands.  The notable examples were Mesa and Flying Mountains.  

Thanks again
