### ISSUE TITLE
Crash on chunk generation

### ISSUE THREAD

**Issue by mrtomwolf** [Team-RTG/Realistic-Terrain-Generation#957]
Updated to RTG 4.1.1.2 snapshot 6 and when I flew around I suddenly got a crash and it crashes for me after a while when I log back in as well. Got some help with the log file and it seems to be a chunk generation issue so I thought I'd send the file to you as well in case it can be of any use.

http://pastebin.com/we7rADnP

**Comment by mrtomwolf** [comment]
Also this:

![2016-09-19_14 45 00](https://cloud.githubusercontent.com/assets/15108756/18632455/cffbc658-7e77-11e6-810b-2529beb908aa.png)

**Comment by whichonespink44** [comment]
You're experiencing these issues (crash & chunk walls) because in the most recent snapshot we made some fundamental changes under the hood... these snapshots are intended for new worlds only (as indicated in big bold red letters on the release notes).

If you want to confirm this, try loading up a new world with the same seed and fly to the location where the crash occurred. If it crashes again, then there's a problem, but I'm betting it will be fine.

Next week we should be releasing a stable version of RTG, but even then, you should create a new world... after that though, you should be able to update to future versions safely, unless the release notes say otherwise.
