### ISSUE TITLE
1.10.2 ticking world crash

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Realistic-Terrain-Generation#993]
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version: forge-1.10.2-12.18.1.2088
- RTG version: RTG-1.10.2-4.1.1.2
##### Issue Description:

Ticking World crash.  Once you find a place that crashes, it keeps crashing in the same way at the same place.
##### Steps to reproduce the issue: (If it's easily reproducible.)

Unknown.  A Placemod item got pasted in at the same time, but I removed that mod and same ticking crash happened.
##### Extra Information:

[crash-2016-10-08_09.08.41-server.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/517346/crash-2016-10-08_09.08.41-server.txt)
[fml-client-latest.zip](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/517349/fml-client-latest.zip)

**Comment by srs-bsns** [comment]
`net.minecraft.util.WeightedRandom#getTotalWeight` is causing an `IllegalArgumentException` in `net.minecraft.util.WeightedRandom#getRandomItem`

`getTotalWeight` returns a summation of the spawn weights of spawnable entities (in this case, `EnumCreatureType.CREATURE`) for a biome, and if the value is _<=0_ it throws the `IllegalArgumentException`, instead of passing a _<=0_ value to `Random`, which would then throw it's own `IllegalArgumentException`.
(GG Mojang, throwing your own exception with less syntax then just letting Random do it! :smug:)

This can not be caused by RTG as we don't add mobs, nor do we alter spawn weights; We simply call `doPopulate` on the chunk. The cause of this will be another mod that adds `EnumCreatureType.CREATURE` type mobs and registers them with erroneous spawn weight values, OR possibly a poorly written CraftTweaker script that erroneously alters the spawn weights (if CraftTweaker has that capability).

@Zygus42 If this is something that you can reproduce easily with the mods you are currently using, I suggest testing for which mod is causing this by removing mods that add friendly mobs one at a time until the crashing stops.

**Comment by Zygus42** [comment]
Sorry - I know you closed this, but it happens on our world build when we have RTG-1.10.2-4.1.1.2 installed, but not with what we're currently using which is RTG-1.10.2-4.1.1.2-snapshot-5.  I haven't tried out the snapshots in-between, so I'm not clear on when the problem has been introduced, but it is quite clearly something to do with RTG in some fashion.  I will do some more testing tomorrow and see what I can find out.
